/* Presentazione wiki statica: nessuna libreria e nessun account richiesto ai lettori. */
(() => {
  "use strict";
  const data = CHRONICLES;
  let destroyMapViewer = null;
  const main = document.getElementById("main-content");
  const menu = document.getElementById("menu-toggle");
  const sidebar = document.getElementById("sidebar");
  const shade = document.getElementById("mobile-shade");
  const backdrop = document.getElementById("search-backdrop");
  const searchInput = document.getElementById("search-input");
  const searchResults = document.getElementById("search-results");

  const sections = [
    {collection: "people", path: "personaggi", title: "Personaggi", icon: "♙", caption: "Volti, incontri e legami", plural: "personaggi"},
    {collection: "places", path: "luoghi", title: "Atlante", icon: "⌖", caption: "Luoghi visitati", plural: "luoghi"},
    {collection: "discoveries", path: "scoperte", title: "Scoperte e misteri", icon: "✧", caption: "Indizi e oggetti", plural: "scoperte"}
  ];
  function esc(value) {return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function page(inner) {return `<div class="content-wrap">${inner}</div>`;}
  function breadcrumb(...items) {return `<nav class="breadcrumb" aria-label="Percorso"><a href="#/">Cronache</a>${items.map(x => `<span aria-hidden="true">›</span>${x.href ? `<a href="${x.href}">${esc(x.label)}</a>` : `<span>${esc(x.label)}</span>`}`).join("")}</nav>`;}
  function title(kicker, heading, desc="") {return `<div class="eyebrow">${esc(kicker)}</div><h1 class="page-title">${esc(heading)}</h1>${desc?`<p class="page-subtitle">${esc(desc)}</p>`:""}`;}
  function linkFor(s, obj) {return `#/${s.path}/${obj.slug}`;}
  function getRelation(slug) {
    for (const s of sections) {const found=data[s.collection].find(x=>x.slug===slug);if(found)return {name:found.name,href:linkFor(s,found)};}
    return null;
  }
  function relations(row) {const links=(row.relations||[]).map(getRelation).filter(Boolean);return links.length ? `<h2 class="section-title rule-title">Voci collegate</h2><div class="related">${links.map(x=>`<a href="${x.href}">${esc(x.name)} ↗</a>`).join("")}</div>`:"";}
  function renderHome() {
    const count=data.chapters.filter(x=>x.published).length;
    return page(`<div class="hero"><img src="assets/forest.svg" alt="Illustrazione stilizzata di una foresta immersa nella nebbia"><div class="hero-content"><div class="hero-label">Atlante e memorie di viaggio</div><h1>Le Cronache<br>di Thespira</h1><p>Luoghi, personaggi e avvenimenti di una compagnia la cui storia è ancora in corso.</p></div></div>
      <div class="feature-grid">
        <section class="panel"><div class="note">Da dove tutto ebbe inizio</div><h2>Capitolo I · Manna e Lilith-Zetto</h2><p>Una rissa in locanda, un furto maldestro e un'antica foresta: il primo incontro della compagnia e una pagina destinata a restare un mistero.</p><a class="button-link" href="#/cronologia/manna">Leggi il capitolo <span>→</span></a></section>
        <section class="panel"><div class="note">Ultima situazione nota</div><h2 class="location-now">${esc(data.current.place)}</h2><p>${esc(data.current.subtitle)}</p><p class="subtle">${esc(data.current.next)}</p></section>
      </div>
      <h2 class="section-title rule-title">Esplora l'archivio</h2>
      <div class="tile-grid"><a class="topic-card" href="#/cronologia"><span class="topic-icon">☷</span><strong>Cronologia</strong><small>${data.chapters.length} archi narrativi · ${count} ${count===1?"pubblicato":"pubblicati"}</small></a>${sections.map(s=>`<a class="topic-card" href="#/${s.path}"><span class="topic-icon">${s.icon}</span><strong>${esc(s.title)}</strong><small>${esc(s.caption)}</small></a>`).join("")}</div>
      <div class="home-map-feature"><img src="assets/mappa-thespira.jpg" alt="Estratto dalla mappa del continente insulare di Thespira" loading="lazy"><div><span class="note">Cartografia del continente</span><h2>La mappa di Thespira</h2><p>Consulta la carta, esplora le regioni e ingrandisci i dettagli direttamente dal browser.</p><a class="button-link" href="#/mappa">Apri la mappa <span>→</span></a></div></div>
      <p class="info-banner">Queste pagine raccolgono soltanto informazioni note alla compagnia. Le voci vengono pubblicate e aggiornate man mano che la cronaca prende forma, senza anticipare i segreti dell'avventura.</p>
      <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
  }
  function renderTimeline() {
    return page(`${breadcrumb({label:"Cronologia"})}${title("Il viaggio", "Cronologia", "Gli eventi della compagnia, in ordine. I capitoli non ancora consultabili verranno aggiunti progressivamente.")}
      ${data.chapters.map(x=>`<article class="chapter-row"><div class="chapter-number">${esc(x.number)}</div><div class="chapter-text"><div class="region">${esc(x.region)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div>${x.published?`<a class="button-link" href="#/cronologia/${x.slug}">Leggi →</a>`:`<span class="small-pill pill-soon">In redazione</span>`}</article>`).join("")}
      <p class="info-banner">La successione dei capitoli segue gli avvenimenti giocati, a partire da Manna. Il materiale preparatorio del DM non viene pubblicato.</p>`);
  }
  const ch1Sections = [
    {id:"la-rissa",title:"1. La rissa al Cervo Sonnacchioso", body:`<p>Le strade dei primi cinque membri della compagnia si incrociano a <a href="#/luoghi/manna">Manna</a>, presso il <a href="#/luoghi/cervo-sonnacchioso">Cervo Sonnacchioso</a>, la locanda di <a href="#/personaggi/wilhelm-codroipo">Wilhelm Codroipo</a>.</p><p>Akros raggiunge il villaggio come guida di un gruppo di viaggiatori che gli hanno promesso un compenso. Derrick, Baldur e Orgen vi arrivano separatamente, in cerca di un luogo dove trascorrere la notte. Tomato si esibisce con la propria <strong>baggopipa</strong> per guadagnarsi vitto e alloggio.</p><p>Quando i viaggiatori accompagnati da Akros si rifiutano di pagarlo, insultano la musica di Tomato e rivolgono offese transfobiche a Wilhelm, la situazione degenera. Baldur, fermo sostenitore dei diritti LGBTQ+, reagisce indignato; Derrick disapprova la prepotenza e i modi rozzi degli stranieri. Akros ha già un conto in sospeso, mentre Orgen non esita a scegliere una parte nella rissa.</p><p>I cinque affrontano e cacciano gli aggressori dalla locanda. Wilhelm, riconoscente, offre loro vitto e alloggio. È il primo episodio in cui i futuri compagni agiscono insieme.</p>`},
    {id:"brann",title:"2. L'incontro con Brann", body:`<p>La mattina seguente il kenku Brann Caradoc tenta un maldestro furto della baggopipa di Tomato e fugge nelle <a href="#/luoghi/foreste-nemorae">Foreste di Nemorae</a>.</p><p>Durante la fuga incontra un branco di lupi, dai quali viene salvato dagli altri cinque avventurieri. Per riconoscenza restituisce lo strumento e ritorna a Manna insieme ai propri soccorritori.</p><p><strong>La compagnia conta ora sei membri:</strong> Akros, Baldur Hawthorne, Brann Caradoc, Derrick Bombarrion, Orgen e Tomato Goldenfield.</p>`},
    {id:"margravio",title:"3. L'incarico del Margravio", body:`<p>Tornati a Manna, gli avventurieri incontrano il sedicente <a href="#/personaggi/margravio">Margravio</a>, un ometto pomposo che amministra il villaggio.</p><p>Chiede loro di fermare <a href="#/personaggi/lilith-zetto">Lilith-Zetto</a>, una Megera Verde responsabile di ripetuti rapimenti di bambini nelle foreste vicine. Una bambina è stata rapita di recente; nessuno dei piccoli scomparsi in precedenza è tornato.</p><p>Il gruppo accetta l'incarico e si inoltra nella foresta.</p>`},
    {id:"spaventapasseri",title:"4. Gli spaventapasseri e il vecchio", body:`<p>Durante la ricerca di Lilith-Zetto, la compagnia affronta cinque spaventapasseri animati. Gli avventurieri riescono a sconfiggerne tre, ma altri due stanno sopraggiungendo.</p><p>A questo punto appare uno <a href="#/personaggi/vecchio">sconosciuto dall'aspetto stanco</a>, che dissolve gli ultimi due spaventapasseri con estrema facilità, limitandosi a posare una mano sulle loro schiene.</p><p>Il vecchio fornisce indicazioni per trovare la megera e offre ospitalità nella propria <a href="#/luoghi/baracca">baracca</a>. Durante la notte, Brann trova e sottrae una <a href="#/scoperte/prima-pagina">pagina ricoperta di simboli incomprensibili</a>.</p>`},
    {id:"megera",title:"5. Lo scontro con Lilith-Zetto", body:`<p>La mattina successiva, seguendo le indicazioni ricevute, la compagnia raggiunge <a href="#/luoghi/antro-megera">l'antro della Megera Verde</a>.</p><p>Gli avventurieri affrontano Lilith-Zetto e riescono a sconfiggerla, ponendo fine alla minaccia per Manna. <strong>La bambina rapita, tuttavia, non può essere salvata.</strong></p>`},
    {id:"messaggio",title:"6. Il messaggio del vecchio", body:`<p>Sulla via del ritorno gli avventurieri raggiungono nuovamente la baracca, ma il suo proprietario è scomparso.</p><p>Il vecchio ha lasciato un messaggio per Brann: sa che il kenku ha sottratto la pagina, ma non ne chiede la restituzione. Desidera invece che Brann la conservi.</p><p>La compagnia torna a Manna portando con sé il documento, di cui nessuno conosce ancora l'origine o il significato.</p>`}
  ];
  const ch2Sections = [
    {id:"selese",title:"1. L’ordine di Selese Arco", body:`<p>Dopo la sconfitta di Lilith-Zetto, la compagnia torna a <a href="#/luoghi/manna">Manna</a> per ricevere la ricompensa e riposarsi al <a href="#/luoghi/cervo-sonnacchioso">Cervo Sonnacchioso</a>. Qui viene raggiunta da quattro guardie guidate da <a href="#/personaggi/selese-arco">Magistra Selese Arco</a>, una donna vestita di bianco, oro e blu.</p><p>Selese si presenta come membro del <strong>Settenario Aureo</strong>, il gruppo d’élite della Chiesa di Amaunator. Accusa gli avventurieri di aver intralciato un’indagine che la Chiesa stava conducendo nelle Foreste di Nemorae, anche in relazione alle attività di Lilith-Zetto.</p><p>Come compensazione, impone al gruppo un incarico: rintracciare e sterminare un accampamento itinerante di nomadi originari di Heliara, che descrive come traditori della Chiesa. L’accampamento si muove nelle terre a nord di Manna. Al termine, la compagnia dovrà fare rapporto a Lantrelle, un avamposto commerciale a nord-est.</p>`},
    {id:"nero",title:"2. L’incontro con Nero", body:`<p>Durante il viaggio verso nord, gli avventurieri incontrano <a href="#/personaggi/nero">Nero</a>, uno sconosciuto interamente vestito di nero e riconoscibile per un vistoso cappello a cilindro.</p><p>La compagnia lo salva da un <strong>androsfinge</strong>. In segno di riconoscenza, Nero consegna ai suoi soccorritori <a href="#/scoperte/anelli-acqua">quattro Anelli del Camminare sull’Acqua</a>.</p>`},
    {id:"arel",title:"3. Arel e l’accampamento", body:`<p>Proseguendo, gli avventurieri soccorrono un bambino di nome <a href="#/personaggi/arel">Arel</a>. Il piccolo appartiene proprio al gruppo di nomadi che Selese ha ordinato di eliminare e, inconsapevolmente, conduce la compagnia al loro <a href="#/luoghi/accampamento-reietti">accampamento</a>.</p><p>L’incontro con gli abitanti non conferma la descrizione fornita dalla Magistra. I reietti si mostrano ospitali; <a href="#/personaggi/brannor">Brannor</a> invita gli avventurieri a condividere la cena e a trascorrere lì la notte.</p>`},
    {id:"assalto",title:"4. L’assalto degli uomini della Chiesa", body:`<p>Durante la cena, un manipolo di uomini con le insegne della Chiesa di Amaunator attacca l’accampamento. Nell’assalto <strong>Arel viene ucciso</strong>.</p><p>Di fronte all’aggressione, gli avventurieri decidono di difendere i reietti, contravvenendo apertamente all’ordine impartito da Selese Arco. La compagnia combatte contro gli assalitori e riesce a sconfiggerli.</p>`},
    {id:"brannor",title:"5. Il racconto di Brannor", body:`<p>Il giorno seguente, Brannor racconta agli avventurieri perché il suo gruppo sia perseguitato. Secondo la sua testimonianza, i reietti sono ex funzionari della Chiesa di Amaunator, fuggiti dopo aver scoperto involontariamente informazioni riservate.</p><p>Il fratello di Brannor gli avrebbe confidato che la Chiesa stava cercando <a href="#/scoperte/antico-diario">un antico diario</a> attraverso un’operazione di massima segretezza. Poco dopo, sarebbe stato ucciso a Heliara. Temendo per la propria vita, Brannor e altri sopravvissuti alla successiva epurazione si erano dati alla fuga.</p><p>Brannor ritiene che Selese sia stata incaricata di eliminare ogni possibile testimone. La compagnia ha ormai scelto di risparmiare e proteggere gli abitanti dell’accampamento. Resta da affrontare la richiesta della Magistra di fare rapporto a Lantrelle.</p>`}
  ];
  const ch3Sections = [
    {id:"falso-rapporto",title:"1. Il falso rapporto", body:`<p>Dopo avere difeso i reietti, gli avventurieri raggiungono <a href="#/luoghi/lantrelle">Lantrelle</a>, dove intendono mentire a <a href="#/personaggi/selese-arco">Selese Arco</a> sull'esito della missione.</p><p><strong>Tomato</strong> prova a sostenere il falso rapporto. Ma <strong>Derrick</strong> si presenta indossando <a href="#/scoperte/armatura-ufficiale">l'armatura recuperata dal corpo di un ufficiale della Chiesa</a>, ucciso durante l'assalto all'accampamento. Selese riconosce l'equipaggiamento e comprende che la compagnia le sta mentendo. Il confronto diventa estremamente teso.</p>`},
    {id:"cato",title:"2. L'intervento di Cato Mirel", body:`<p>Accanto a Selese si trova <a href="#/personaggi/cato-mirel">Cato Mirel</a>, un ragazzino biondo dall'aria allegra e bonaria che si presenta come Magistro del Settenario Aureo.</p><p>Con apparente candore, Cato suggerisce che Selese potesse essersi aspettata un simile esito: tra gli uomini inviati contro i reietti vi erano <strong>due ufficiali che la Magistra considerava «impuri»</strong>, accusati di intrattenere una relazione omosessuale. Secondo l'ipotesi esposta da Cato, Selese avrebbe potuto trarre vantaggio sia dall'eliminazione dei reietti, sia dalla morte degli ufficiali.</p><p>L'osservazione, pronunciata con leggerezza sorprendente, rivela un intuito assai più tagliente di quanto lascino supporre i modi del giovane Magistro. Selese si irrigidisce, ma non insiste. <strong>Il calcolo attribuitole resta un'interpretazione di Cato, non una confessione della Magistra.</strong></p>`},
    {id:"missione",title:"3. Un nuovo test: la pagina di Obsydra", body:`<p>Rivolgendosi agli avventurieri con aria furba, Cato propone un altro «test»: recuperare <a href="#/scoperte/pagina-obsydra">una pagina rinvenuta nelle miniere di Obsydra</a>, la principale città-stato del Surturheim.</p><p>La Chiesa di Amaunator ritiene di avere diritto alla reliquia, ma Cato non è riuscito a ottenerla. Gli abitanti del Surturheim, perlopiù devoti al Culto del Fuoco, guardano con diffidenza chi porta le insegne della Chiesa. Un gruppo di avventurieri sconosciuti potrebbe muoversi con maggiore libertà.</p><p>Cato appare cordiale, persino ridanciano, ma mostra anche una notevole capacità di leggere persone e circostanze. Alla compagnia dà l'impressione di essere sinceramente benevolo. Prima di congedarla, consiglia di passare dall'<a href="#/luoghi/emporio-brambilla">Emporio del Brambilla</a>.</p>`},
    {id:"brambilla",title:"4. L'Emporio del Brambilla", body:`<p>Gli avventurieri seguono il suggerimento e visitano l'<a href="#/luoghi/emporio-brambilla">Emporio del Brambilla</a>, dove incontrano un commerciante brianzolo dall'accento milanese, dai modi energici e da un'indole spietatamente affaristica.</p><p>Il carattere sanguigno e caricaturale del <a href="#/personaggi/brambilla">Brambilla</a> rende la visita un episodio particolarmente divertente. La compagnia acquista alcuni generi vari, senza che emergano oggetti di rilievo per la cronaca, quindi può proseguire verso il Surturheim e la missione affidata da Cato.</p>`}
  ];
  const ch4Sections = [
    {id:"verso-surturheim",title:"1. La strada verso il Surturheim",body:`<p>Lasciata Lantrelle, la compagnia prosegue verso Obsydra per cercare la misteriosa pagina segnalata da Magistro Cato Mirel. Il viaggio segue il corso del grande <a href="#/luoghi/lirion">fiume Lirion</a>, conducendo gli avventurieri fuori dalle Foreste di Nemorae e verso i paesaggi montuosi del Surturheim. Il territorio diventa progressivamente più spoglio, dominato da rilievi scoscesi e pendii rocciosi.</p><p>Lungo la strada, alcuni minatori fermano il gruppo e chiedono aiuto. Nella <a href="#/luoghi/miniera-brugheroccia">miniera</a> del vicino borgo di <a href="#/luoghi/brugheroccia">Brugheroccia</a> si stanno verificando fenomeni inspiegabili: rumori misteriosi, un'oscurità insolitamente profonda e una persistente sensazione di gelo.</p><p><strong>Un lavoratore si trova ancora all'interno.</strong> Benché la richiesta sia estranea alla missione affidata da Cato, la preoccupazione dei minatori per il compagno convince gli avventurieri a intervenire.</p>`},
    {id:"gallerie",title:"2. L'esplorazione della miniera",body:`<p>La compagnia si addentra nelle gallerie della miniera di Brugheroccia. Il percorso presenta alcune diramazioni, ma gli avventurieri riescono ad avanzare senza particolari difficoltà, almeno inizialmente.</p><p>Un crollo ostruisce una delle vie, costringendo il gruppo a una breve deviazione. Nel corso dell'esplorazione vengono scoperti alcuni <strong>Mephit di terra</strong>, che gli avventurieri affrontano e sconfiggono.</p><p>Superato anche questo ostacolo, la compagnia prosegue verso la parte della miniera in cui sembra concentrarsi la presenza inquietante segnalata dai lavoratori.</p>`},
    {id:"babau",title:"3. Il Babau",body:`<p>In una camera sotterranea, gli avventurieri scorgono qualcosa di anomalo: un'oscurità ancora più profonda di quella che già avvolge le gallerie. Da essa sporge <strong>il corpo smembrato del minatore disperso</strong>. Ogni speranza di trarlo in salvo svanisce.</p><p><strong>Baldur</strong> si avvicina incautamente ai resti e viene colpito di sorpresa dalla creatura nascosta nell'oscurità. La compagnia si trova così ad affrontare un <a href="#/scoperte/babau-brugheroccia">Babau</a>, un demone abissale riconoscibile dalle descrizioni tramandate nelle leggende.</p><p>Lo scontro si rivela impegnativo, ma gli avventurieri riescono infine ad abbattere il mostro.</p><p>La presenza di una creatura simile è insolita persino per Thespira. Nelle Foreste di Nemorae, <a href="#/personaggi/vecchio">il misterioso vecchio</a> che aveva aiutato il gruppo contro gli spaventapasseri aveva già accennato a qualcosa di terribile che stava accadendo sul continente. L'incontro con il Babau potrebbe assumere un significato alla luce di quell'avvertimento, ma la compagnia non dispone ancora di elementi sufficienti per comprenderne l'origine o stabilire collegamenti precisi.</p>`},
    {id:"crucitti",title:"4. Brugheroccia e il Crucitti",body:`<p>Eliminata la minaccia, la compagnia raggiunge <a href="#/luoghi/brugheroccia">Brugheroccia</a>, un piccolo e dignitoso borgo montano, circondato da pendii spogli e scoscesi. Dall'abitato si può osservare, più a valle, il corso del Lirion.</p><p>Gli avventurieri ricevono una riconoscenza sincera, benché priva di grandi festeggiamenti. A occuparsi di loro è soprattutto <a href="#/personaggi/crucitti"><strong>il Crucitti</strong></a>, un uomo sulla settantina, pelato e con un folto pizzetto, che ricopre contemporaneamente le cariche di sindaco, locandiere e titolare della locale impresa di passamaneria.</p><p>Il Crucitti è energico, dai modi bruschi e quasi aggressivi, abituato a impartire ordini ai quali gli abitanti sembrano rispondere con sollecitudine. Dietro l'atteggiamento spiccio e un po' caricaturale, tuttavia, si rivela una persona onesta e affidabile.</p><p>Per ringraziare la compagnia, il Crucitti consegna agli avventurieri una ricompensa in oro e offre loro vitto e alloggio gratuiti. Il gruppo accetta l'ospitalità e trascorre la notte a Brugheroccia.</p>`},
    {id:"citta-fuoco",title:"5. Le città del fuoco",body:`<p>Durante il soggiorno, il Crucitti condivide con gli avventurieri alcune considerazioni sulla situazione politica e religiosa del Surturheim.</p><p>Secondo il suo racconto, le due principali città-stato della regione, <strong>Obsydra e Pyrocladion</strong>, stanno attraversando un periodo di buoni rapporti dopo una storia segnata da numerosi contrasti. Il Crucitti ritiene che questo riavvicinamento sia dovuto all'ascesa del <a href="#/scoperte/culto-fuoco">Culto del Fuoco</a>, al quale entrambe le città sembrano aver aderito con entusiasmo.</p><p>Il tema era già stato indirettamente sollevato da <a href="#/personaggi/cato-mirel">Cato Mirel</a>, che aveva indicato la diffusione del culto come una delle ragioni della diffidenza degli abitanti del Surturheim verso la Chiesa di Amaunator. Le parole del Crucitti forniscono dunque alla compagnia qualche informazione in più sulle terre verso cui si sta dirigendo, <strong>pur rimanendo una sua interpretazione delle vicende locali</strong>.</p><p>Conclusa la permanenza a Brugheroccia, gli avventurieri possono riprendere il viaggio verso Obsydra.</p>`}
  ];
  const ch5Sections = [
    {id:"arrivo",title:"1. La città di pietra e vapore",body:`<p>Dopo aver lasciato <a href="#/luoghi/brugheroccia">Brugheroccia</a>, la compagnia prosegue il viaggio lungo il <a href="#/luoghi/lirion">Lirion</a> fino a raggiungere <a href="#/luoghi/obsydra"><strong>Obsydra</strong></a>, una delle principali città-stato del Surturheim.</p><p>La città si sviluppa sulle pendici scoscese delle montagne, attraversata interamente dall’imponente corso del fiume. Massicci edifici di pietra scura, ponti, torri e strutture industriali si sovrappongono su diversi livelli, formando un paesaggio urbano severo e monumentale.</p><p>Vapori e fumo si levano dalle attività produttive, mentre il rumore incessante di martelli, officine e grandi meccanismi accompagna la vita cittadina. Carri carichi di minerali percorrono le strade e il lavoro sembra scandire ogni momento della giornata. Obsydra è una città operosa, caotica e industrialmente progredita, la cui prosperità appare strettamente legata allo sfruttamento delle risorse minerarie.</p><p>Gli avventurieri fanno ingresso attraverso il <a href="#/luoghi/varco-scoria"><strong>Varco della Scoria</strong></a>, una monumentale porta di basalto affiancata da statue di guerrieri armati di martello. Sopra l’accesso campeggia il motto <em>«Il fuoco purifica. Il fuoco forgia.»</em> La compagnia viene sottoposta a un ordinario controllo da parte delle guardie cittadine, tra le quali figura anche un accolito del Culto del Fuoco. Non si verificano particolari difficoltà.</p><p>Il gruppo prende alloggio presso <a href="#/luoghi/cervo-dormiveglia">il Cervo in Dormiveglia</a> e comincia a cercare informazioni sulla pagina che <a href="#/personaggi/cato-mirel">Cato Mirel</a> ha chiesto di recuperare.</p>`},
    {id:"bevute",title:"2. La sfida alla Locanda del Vapore",body:`<p>Le prime ricerche conducono gli avventurieri alla <a href="#/luoghi/locanda-vapore"><strong>Locanda del Vapore</strong></a>, un locale rumoroso frequentato soprattutto dai minatori di Obsydra. Gli avventori accolgono con diffidenza le domande degli sconosciuti sulla reliquia rinvenuta nelle miniere.</p><p>Tra loro si trovano <a href="#/personaggi/bram-ferrovena">Bram Ferrovena</a>, un minatore dalla corporatura imponente e dalla barba intrecciata con frammenti di quarzo, <a href="#/personaggi/dorna-spaccapietra">Dorna Spaccapietra</a>, una nana pratica e sospettosa, e <a href="#/personaggi/lerrik-occhio-storto">Lerrik «Occhio Storto»</a>, un uomo inquieto e superstizioso.</p><p>Per conquistare la fiducia dei presenti, gli avventurieri devono dimostrare di essere persone degne di rispetto. Bram propone una gara di bevute e <strong>Baldur Hawthorne</strong> accetta di rappresentare la compagnia. Il chierico affronta la sfida, finendo per ubriacarsi, ma la sua determinazione conquista la simpatia di Bram e dei suoi compagni.</p><p>Superata la diffidenza iniziale, i minatori raccontano che nelle profondità delle miniere è stata rinvenuta una pagina dalle proprietà insolite. Il documento sarebbe stato portato alla Biblioteca cittadina per poi sparire misteriosamente. Circolano inoltre voci sulla scomparsa di un minatore, forse proprio colui che aveva effettuato il ritrovamento. La compagnia decide quindi di recarsi alla Biblioteca.</p>`},
    {id:"biblioteca",title:"3. Il mistero della Biblioteca Olivetti",body:`<p>Presso la <a href="#/luoghi/biblioteca-olivetti"><strong>Biblioteca Olivetti</strong></a>, gli avventurieri incontrano <a href="#/personaggi/orisel-tharn">Dama Orisel Tharn</a>, un’anziana nana dal carattere severo, responsabile dell’istituzione. La direttrice si mostra inizialmente reticente, ma le insistenti domande sulla reliquia la mettono visibilmente in difficoltà.</p><p>Ammette che il documento era stato consegnato alla Biblioteca e che la sua natura insolita aveva suscitato inquietudine. Nei giorni successivi al ritrovamento, diverse persone si erano interessate alla pagina: un giovane biondo appartenente alla Chiesa di Amaunator aveva chiesto informazioni, mentre un altro uomo si era presentato pretendendone la restituzione, venendo allontanato.</p><p>Poco dopo, il documento era stato sottratto alla Biblioteca. Orisel rivela inoltre che <a href="#/personaggi/mira-voss">Mira Voss</a> si era recata da lei per cercare notizie del marito scomparso, lasciando un indirizzo al quale essere eventualmente ricontattata. Gli avventurieri decidono di seguire questa nuova pista.</p>`},
    {id:"famiglia",title:"4. La famiglia Voss e Sefra «Tre-Dita»",body:`<p>La compagnia raggiunge l’abitazione di <a href="#/personaggi/mira-voss">Mira Voss</a>, una sarta molto bella e profondamente preoccupata per la sorte del marito.</p><p><a href="#/personaggi/teren-voss"><strong>Teren Voss</strong></a> è un minatore esperto, ma insoddisfatto della propria posizione. Sebbene i concittadini lo trattino con simpatia, il loro atteggiamento bonariamente condiscendente alimenta in lui la sensazione di essere considerato un uomo di poco conto. Il ritrovamento della pagina gli aveva offerto la prospettiva di distinguersi e ottenere finalmente il riconoscimento desiderato.</p><p>Mira racconta che il marito aveva scoperto il documento durante il lavoro, ma che il capoturno gliel’aveva confiscato per consegnarlo alla Biblioteca. Convinto di aver trovato qualcosa di prezioso, Teren aveva cercato di recuperare la reliquia. Successivamente era scomparso.</p><p>Usciti dall’abitazione, gli avventurieri incontrano <a href="#/personaggi/sefra-tre-dita"><strong>Sefra «Tre-Dita»</strong></a>, una mezzelfa dall’aspetto trasandato, il viso olivastro e triangolare, i capelli radi e spettinati e un ghigno perennemente allusivo. Indossa una cappa viola scuro e alla mano sinistra conserva soltanto tre dita.</p><p>Sefra opera negli ambienti del mercato nero di Obsydra e ammette di aver sottratto la pagina dalla Biblioteca su richiesta di Teren. La reliquia, tuttavia, non sembrava avere alcun valore commerciale, per quanto mostrasse proprietà inspiegabili.</p><p>Deluso dalla valutazione, Teren aveva deciso di tornare nelle profondità delle miniere, convinto di poter trovare altri reperti simili. La sua destinazione era <a href="#/luoghi/cava-obsydra"><strong>la Cava</strong></a>.</p>`},
    {id:"cava",title:"5. La discesa nella Cava",body:`<p>Le successive verifiche presso le <a href="#/luoghi/miniere-obsydra">miniere</a> confermano che Teren è entrato nelle gallerie profonde senza tornare alla superficie. La compagnia decide di raggiungerlo.</p><p>Ad accompagnare gli avventurieri è <a href="#/personaggi/rurik-pietracorta"><strong>Rurik Pietracorta</strong></a>, un vecchio minatore che conosce gli accessi alle parti più antiche degli scavi.</p><p>La <a href="#/luoghi/cava-obsydra">Cava</a> è una gigantesca voragine scoperta durante l’avanzamento delle attività minerarie. L’ambiente dà l’impressione di essere rimasto abbandonato per un tempo lunghissimo e gli stessi lavoratori di Obsydra temono di addentrarvisi. Rurik guida il gruppo fino all’ingresso della zona più profonda, ma si rifiuta di procedere oltre.</p><p>Gli avventurieri proseguono da soli. Dopo alcune ore di esplorazione riescono a trovare <strong>Teren Voss</strong>, ancora in buone condizioni e impegnato nella ricerca di altre pagine. L’uomo si convince che sia opportuno tornare in superficie e accetta di accompagnare il gruppo.</p><p>Durante il percorso, tuttavia, un cedimento del terreno, apparentemente favorito dal passaggio degli avventurieri, provoca un crollo che impedisce loro di ripercorrere la via d’accesso. La compagnia rimane bloccata nelle profondità della Cava.</p>`},
    {id:"paladino",title:"6. Il Vecchio Paladino Oscuro",body:`<p>Nelle profondità degli scavi, gli avventurieri si imbattono in un guerriero dall’aspetto inquietante. La figura ricorda un elfo alto e possente, pallido, con un volto allungato segnato da rughe profonde, occhi infossati e apparentemente privi di espressione, una bocca esangue e capelli scuri tagliati irregolarmente.</p><p>Indossa una pesante armatura, un tempo probabilmente magnifica, ora annerita dalla polvere e dall’ossidazione. L’impressione non è tanto quella di un uomo anziano, quanto di una creatura appartenente a un’epoca remota.</p><p>Il <a href="#/personaggi/paladino-oscuro"><strong>Vecchio Paladino Oscuro</strong></a> attacca immediatamente la compagnia, senza tentare alcun dialogo. Lo scontro è impegnativo. Durante il combattimento, però, l’avversario manifesta un comportamento insolito nei confronti di <strong>Derrick Bombarrion</strong>: lo osserva con incredulità e scuote ripetutamente la testa, come se il suo volto risvegliasse un ricordo impossibile.</p><p>Gli avventurieri riescono infine a sconfiggerlo. Ormai morente, il guerriero chiama Derrick a sé, pronunciando faticosamente il suo nome. Con gli ultimi barlumi di coscienza lo accusa di aver tradito qualcuno chiamato <strong>Aurel</strong> e lo implora di non consegnare la pagina alla Chiesa di Amaunator.</p><p>Derrick, incapace di comprendere il significato di quelle parole, cerca di ottenere spiegazioni. Il guerriero non riesce a fornirgliele. Prima di morire gli consegna la propria arma, un’antica <a href="#/scoperte/spada-giuramento"><strong>Spada lunga del Giuramento</strong></a>, dalla lama annerita e fredda al tatto e dall’elsa segnata da incisioni consumate.</p><p>Il Paladino spira con un tenue sorriso sulle labbra, quasi avesse finalmente trovato riposo. La compagnia recupera anche trenta monete d’oro. L’identità del guerriero e il suo legame con Derrick rimangono sconosciuti.</p>`},
    {id:"pagine",title:"7. Il ritorno e la seconda pagina",body:`<p>Superato lo scontro, Teren rivela di conoscere un percorso alternativo per uscire dalla Cava. Conduce gli avventurieri attraverso stretti cunicoli fino a raggiungere le gallerie ancora utilizzate dai minatori, dalle quali il gruppo può risalire in superficie servendosi di un montacarichi.</p><p>Tornati a Obsydra, gli avventurieri accompagnano Teren dalla moglie. È qui che emerge un particolare decisivo: <strong>la pagina non si trovava nella Cava</strong>. Teren l’aveva lasciata a Mira prima di avventurarsi nuovamente nelle miniere.</p><p>La donna ammette di averlo taciuto deliberatamente. Temeva che, una volta ottenuto il documento, gli avventurieri avrebbero rinunciato a cercare suo marito. Riconoscente per il suo ritorno, Mira consegna infine <a href="#/scoperte/pagina-obsydra">la reliquia</a> alla compagnia, nonostante una certa riluttanza di Teren.</p><p>Gli avventurieri possono così confrontare la pagina di Obsydra con <a href="#/scoperte/prima-pagina">quella sottratta da Brann</a> nella baracca del misterioso vecchio delle Foreste di Nemorae. I due documenti sembrano appartenere alla stessa tipologia: sono ricoperti di simboli differenti, ma presentano caratteristiche materiali straordinariamente simili.</p><p>La compagnia scopre inoltre che le pagine sembrano indistruttibili. Anche tentando di danneggiarle, non riesce ad alterarne la struttura. Gli avventurieri possiedono ora due frammenti di un mistero di cui ignorano ancora origine e significato.</p>`},
    {id:"roncenoir",title:"8. Sefra e la via verso Roncenoir",body:`<p>Alla <a href="#/luoghi/locanda-vapore">Locanda del Vapore</a>, la compagnia incontra nuovamente alcune conoscenze cittadine, tra cui Bram Ferrovena, Dorna Spaccapietra e Lerrik «Occhio Storto». Tra loro ricompare anche <a href="#/personaggi/sefra-tre-dita">Sefra «Tre-Dita»</a>.</p><p>La mezzelfa si mostra sempre più incuriosita dalle pagine. Non riesce a comprendere perché documenti apparentemente privi di valore commerciale suscitino tanto interesse, ma proprio questa contraddizione la spinge a indagare ulteriormente. La curiosità prevale infine sul desiderio di ricavarne un profitto.</p><p>Sefra racconta agli avventurieri di un suo vecchio mentore, <strong>Giotis Pana</strong>, un elfo studioso di antichità che, secondo le sue ultime informazioni, risiede a <strong>Roncenoir</strong>, nelle zone settentrionali delle Foreste di Nemorae. Ritiene che Giotis possa essere in grado di interpretare i segni che ricoprono le pagine.</p><p>La compagnia decide quindi di seguire questa nuova pista. La scelta comporta una conseguenza importante: gli avventurieri <strong>non tornano a Lantrelle per consegnare la reliquia a Cato Mirel</strong>. La decisione è condivisa dal gruppo e segna un ulteriore allontanamento dagli incarichi ricevuti dalla Chiesa di Amaunator.</p><p>Prima della partenza, <strong>Orgen rimane presso l’abitazione dei Voss</strong>. La compagnia prosegue quindi il viaggio senza di lui. Gli altri cinque avventurieri scelgono la strada che conduce verso i canyon a ovest di Obsydra, diretti a Roncenoir.</p>`},
  ];
  function renderChapter(slug) {
    if(slug==="obsydra"){
      const sectionsHtml=ch5Sections.map(x=>`<section id="${x.id}"><h2>${x.title}</h2>${x.body}</section>`).join("");
      return page(`${breadcrumb({label:"Cronologia",href:"#/cronologia"},{label:"V · Obsydra e il Vecchio Paladino Oscuro"})}${title("Capitolo V · Surturheim","Obsydra e il Vecchio Paladino Oscuro")}
        <div class="meta-line"><span class="small-pill pill-ready">Capitolo pubblicato</span><span class="small-pill">Obsydra · Surturheim · La Cava</span></div>
        <div class="chapter-lead">La ricerca di una pagina nelle miniere conduce a un minatore scomparso, a un guerriero che sembra riconoscere Derrick e a una decisione che allontana la compagnia dalla Chiesa.</div>
        <div class="article-layout"><article class="article-body">${sectionsHtml}
        <section class="summary-box" aria-label="Riepilogo del capitolo"><h3>Il capitolo in breve</h3><ul><li>La compagnia raggiunge Obsydra, grande città mineraria e industriale del Surturheim.</li><li>Baldur affronta Bram Ferrovena in una gara di bevute e ottiene la fiducia dei minatori.</li><li>Le indagini alla Biblioteca Olivetti e presso i Voss conducono alla Cava.</li><li>Gli avventurieri trovano Teren e sconfiggono il Vecchio Paladino Oscuro, che riconosce Derrick e pronuncia il nome di Aurel.</li><li>Mira consegna una seconda pagina, simile a quella di Brann.</li><li>Sefra consiglia Giotis Pana a Roncenoir; la compagnia non torna a fare rapporto a Cato.</li><li>Orgen rimane a Obsydra, mentre gli altri cinque riprendono il viaggio.</li></ul></section>
        <h2 class="section-title rule-title">Da approfondire</h2><div class="related"><a href="#/luoghi/obsydra">Obsydra ↗</a><a href="#/luoghi/cava-obsydra">La Cava ↗</a><a href="#/personaggi/teren-voss">Teren Voss ↗</a><a href="#/personaggi/mira-voss">Mira Voss ↗</a><a href="#/personaggi/sefra-tre-dita">Sefra «Tre-Dita» ↗</a><a href="#/personaggi/paladino-oscuro">Paladino Oscuro ↗</a><a href="#/scoperte/pagina-obsydra">Seconda pagina ↗</a><a href="#/scoperte/spada-giuramento">Spada del Giuramento ↗</a></div>
        </article><nav class="toc" aria-label="In questo capitolo"><strong>In questo capitolo</strong>${ch5Sections.map(x=>`<a href="#${x.id}" data-toc="${x.id}">${esc(x.title)}</a>`).join("")}</nav></div>
        <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
    }
    if(slug==="brugheroccia"){
      const sectionsHtml=ch4Sections.map(x=>`<section id="${x.id}"><h2>${x.title}</h2>${x.body}</section>`).join("");
      return page(`${breadcrumb({label:"Cronologia",href:"#/cronologia"},{label:"IV · Il Babau di Brugheroccia"})}${title("Capitolo IV · Surturheim","Il Babau di Brugheroccia")}
        <div class="meta-line"><span class="small-pill pill-ready">Capitolo pubblicato</span><span class="small-pill">Lirion · Brugheroccia · Surturheim</span></div>
        <div class="chapter-lead">Una richiesta di soccorso lungo la strada per Obsydra conduce gli avventurieri nelle profondità di una miniera, dove li attende una creatura abissale.</div>
        <div class="article-layout"><article class="article-body">${sectionsHtml}
        <section class="summary-box" aria-label="Riepilogo del capitolo"><h3>Il capitolo in breve</h3><ul><li>Alcuni minatori chiedono alla compagnia di soccorrere un compagno rimasto nella miniera.</li><li>Gli avventurieri aggirano un crollo e sconfiggono alcuni Mephit di terra.</li><li>Trovano il minatore ucciso e affrontano un Babau, che riescono ad abbattere.</li><li>Il Crucitti li ricompensa con oro, vitto e alloggio.</li><li>Il Crucitti riferisce del riavvicinamento tra Obsydra e Pyrocladion, che attribuisce all'influenza del Culto del Fuoco.</li></ul></section>
        <h2 class="section-title rule-title">Da approfondire</h2><div class="related"><a href="#/luoghi/brugheroccia">Brugheroccia ↗</a><a href="#/luoghi/miniera-brugheroccia">La miniera ↗</a><a href="#/personaggi/crucitti">Il Crucitti ↗</a><a href="#/scoperte/babau-brugheroccia">Il Babau ↗</a><a href="#/scoperte/culto-fuoco">Il Culto del Fuoco ↗</a></div>
        </article><nav class="toc" aria-label="In questo capitolo"><strong>In questo capitolo</strong>${ch4Sections.map(x=>`<a href="#${x.id}" data-toc="${x.id}">${esc(x.title)}</a>`).join("")}</nav></div>
        <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
    }
    if(slug==="lantrelle"){
      const sectionsHtml=ch3Sections.map(x=>`<section id="${x.id}"><h2>${x.title}</h2>${x.body}</section>`).join("");
      return page(`${breadcrumb({label:"Cronologia",href:"#/cronologia"},{label:"III · Il rapporto di Lantrelle"})}${title("Capitolo III · Nemorae","Il rapporto di Lantrelle")}
        <div class="meta-line"><span class="small-pill pill-ready">Capitolo pubblicato</span><span class="small-pill">Lantrelle · Verso Surturheim</span></div>
        <div class="chapter-lead">Un'armatura riconosciuta, una menzogna scoperta e il sorprendente intervento di Cato Mirel conducono la compagnia verso una nuova pagina misteriosa.</div>
        <div class="article-layout"><article class="article-body">${sectionsHtml}
        <section class="summary-box" aria-label="Riepilogo del capitolo"><h3>Il capitolo in breve</h3><ul><li>Tomato tenta di mentire a Selese, ma l'armatura indossata da Derrick tradisce la compagnia.</li><li>Cato ipotizza che Selese potesse trarre vantaggio dalla morte dei reietti o di due ufficiali da lei giudicati «impuri».</li><li>Selese non insiste; Cato affida alla compagnia il recupero di una pagina a Obsydra.</li><li>Gli avventurieri visitano l'Emporio del Brambilla e acquistano generi vari.</li></ul></section>
        <h2 class="section-title rule-title">Da approfondire</h2><div class="related"><a href="#/personaggi/selese-arco">Selese Arco ↗</a><a href="#/personaggi/cato-mirel">Cato Mirel ↗</a><a href="#/personaggi/brambilla">Il Brambilla ↗</a><a href="#/luoghi/lantrelle">Lantrelle ↗</a><a href="#/luoghi/emporio-brambilla">Emporio del Brambilla ↗</a><a href="#/scoperte/pagina-obsydra">La pagina di Obsydra ↗</a></div>
        </article><nav class="toc" aria-label="In questo capitolo"><strong>In questo capitolo</strong>${ch3Sections.map(x=>`<a href="#${x.id}" data-toc="${x.id}">${esc(x.title)}</a>`).join("")}</nav></div>
        <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
    }
    if(slug==="reietti"){
      const sectionsHtml=ch2Sections.map(x=>`<section id="${x.id}"><h2>${x.title}</h2>${x.body}</section>`).join("");
      return page(`${breadcrumb({label:"Cronologia",href:"#/cronologia"},{label:"II · L’ordine di Selese Arco"})}${title("Capitolo II · Nemorae","L’ordine di Selese Arco")}
        <div class="meta-line"><span class="small-pill pill-ready">Capitolo pubblicato</span><span class="small-pill">Manna · Terre a nord del villaggio</span></div>
        <div class="chapter-lead">L’incontro con il Settenario Aureo, la ricerca dei reietti e la decisione della compagnia di opporsi alla Chiesa di Amaunator.</div>
        <div class="article-layout"><article class="article-body">${sectionsHtml}
        <section class="summary-box" aria-label="Riepilogo del capitolo"><h3>Il capitolo in breve</h3><ul><li>Selese Arco ordina di eliminare un accampamento di nomadi accusati di tradimento.</li><li>La compagnia salva Nero da un androsfinge e riceve quattro anelli magici.</li><li>Il bambino Arel conduce gli avventurieri all’accampamento, dove Brannor li ospita.</li><li>Uomini della Chiesa assaltano il campo e uccidono Arel; gli avventurieri difendono i reietti.</li><li>Brannor riferisce della ricerca segreta di un antico diario da parte della Chiesa.</li></ul></section>
        <h2 class="section-title rule-title">Da approfondire</h2><div class="related"><a href="#/personaggi/selese-arco">Selese Arco ↗</a><a href="#/personaggi/nero">Nero ↗</a><a href="#/personaggi/arel">Arel ↗</a><a href="#/personaggi/brannor">Brannor ↗</a><a href="#/luoghi/accampamento-reietti">Accampamento dei reietti ↗</a><a href="#/scoperte/antico-diario">L’antico diario ↗</a></div>
        </article><nav class="toc" aria-label="In questo capitolo"><strong>In questo capitolo</strong>${ch2Sections.map(x=>`<a href="#${x.id}" data-toc="${x.id}">${esc(x.title)}</a>`).join("")}</nav></div>
        <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
    }
    if(slug!=="manna")return renderNotFound();
    const sectionsHtml=ch1Sections.map(x=>`<section id="${x.id}"><h2>${x.title}</h2>${x.body}</section>`).join("");
    return page(`${breadcrumb({label:"Cronologia",href:"#/cronologia"},{label:"I · Manna e Lilith-Zetto"})}${title("Capitolo I · Nemorae","Manna e Lilith-Zetto")}
      <div class="meta-line"><span class="small-pill pill-ready">Capitolo pubblicato</span><span class="small-pill">Manna · Foreste di Nemorae</span></div>
      <div class="chapter-lead">La nascita della compagnia, la minaccia di una Megera Verde e il ritrovamento di una pagina indecifrabile.</div>
      <div class="article-layout"><article class="article-body">${sectionsHtml}
      <section class="summary-box" aria-label="Riepilogo del capitolo"><h3>Il capitolo in breve</h3><ul><li>La compagnia si forma a Manna, tra una rissa e un incontro con un branco di lupi.</li><li>Il Margravio incarica gli avventurieri di fermare Lilith-Zetto.</li><li>Il vecchio della foresta li aiuta e Brann sottrae una misteriosa pagina.</li><li>Lilith-Zetto viene sconfitta, ma la bambina rapita non può essere salvata.</li></ul></section>
      <h2 class="section-title rule-title">Da approfondire</h2><div class="related"><a href="#/scoperte/prima-pagina">La prima pagina ↗</a><a href="#/personaggi/vecchio">Il vecchio della foresta ↗</a><a href="#/personaggi/lilith-zetto">Lilith-Zetto ↗</a><a href="#/luoghi/manna">Manna ↗</a></div>
      </article><nav class="toc" aria-label="In questo capitolo"><strong>In questo capitolo</strong>${ch1Sections.map(x=>`<a href="#${x.id}" data-toc="${x.id}">${esc(x.title)}</a>`).join("")}</nav></div>
      <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
  }
  function renderCollection(s) {
    const items=data[s.collection];
    const mapIntro = s.collection === "places" ? `<a class="atlas-map-teaser" href="#/mappa"><img src="assets/mappa-thespira.jpg" alt="Mappa illustrata di Thespira, con regioni e città" loading="lazy"><span><small>Cartografia</small><strong>La mappa di Thespira</strong><em>Apri la carta geografica, ingrandisci e spostati per esplorare i dettagli.</em><b>Consulta la mappa →</b></span></a>` : "";
    return page(`${breadcrumb({label:s.title})}${title("L'enciclopedia",s.title,`${items.length} ${s.plural} già documentati. Le voci sono aggiornate soltanto con informazioni conosciute dalla compagnia.`)}
      ${mapIntro}<div class="card-grid">${items.map(x=>`<a class="entry-card" href="${linkFor(s,x)}"><div class="eyebrow">${esc(x.role||x.type)}</div><h3>${esc(x.name)}</h3><p>${esc(x.intro)}</p><div class="arrow">Apri la scheda →</div></a>`).join("")}</div>
      <p class="info-banner">Le illustrazioni definitive compariranno nelle singole schede: non verranno pubblicati i Character Pose Sheet utilizzati per definire il design dei personaggi.</p>`);
  }
  function renderEntry(s,slug) {
    const item=data[s.collection].find(x=>x.slug===slug);
    if(!item)return renderNotFound();
    const details=s.collection==="people"?[{label:"Ruolo",val:item.role},{label:"Incontrato a",val:item.where}]:s.collection==="places"?[{label:"Categoria",val:item.type},{label:"Regione",val:item.region}]:[{label:"Tipo",val:item.type},{label:"Stato",val:item.state}];
    const facts=item.facts.map(x=>`<li>${esc(x)}</li>`).join("");
    const visual=item.image?`<div class="profile-symbol profile-portrait"><img src="${esc(item.image)}" alt="Ritratto illustrato di ${esc(item.name)}" loading="lazy"></div>`:`<div class="profile-symbol" aria-label="Illustrazione non ancora disponibile"><span>${s.icon}</span><small>Ritratto da inserire</small></div>`;
    return page(`${breadcrumb({label:s.title,href:`#/${s.path}`},{label:item.name})}${title(s.title,item.name)}
      <div class="profile-top">${visual}<div class="profile-brief"><p>${esc(item.intro)}</p><dl>${details.map(x=>`<dt>${esc(x.label)}</dt><dd>${esc(x.val)}</dd>`).join("")}</dl></div></div>
      <h2 class="section-title rule-title">Cosa sa la compagnia</h2><ul class="fact-list">${facts}</ul>
      ${item.questions?`<h2 class="section-title rule-title">Domande aperte</h2><ul class="fact-list">${item.questions.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:""}
      ${relations(item)}<div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
  }
  function renderMap() {
    return page(`${breadcrumb({label:"Atlante",href:"#/luoghi"},{label:"Mappa di Thespira"})}${title("Cartografia di Thespira","La mappa del continente","La carta geografica delle terre di Thespira. Puoi ingrandirla e spostarla per leggere i dettagli.")}
      <div class="map-frame" id="map-frame">
        <div class="map-tools" role="toolbar" aria-label="Comandi della mappa">
          <div class="map-tools-title"><span aria-hidden="true">✧</span><strong>Thespira</strong><small>Mappa del continente</small></div>
          <div class="map-tool-actions">
            <button type="button" data-map="minus" aria-label="Riduci ingrandimento" title="Riduci">−</button>
            <output id="map-zoom" aria-label="Ingrandimento corrente">100%</output>
            <button type="button" data-map="plus" aria-label="Aumenta ingrandimento" title="Ingrandisci">+</button>
            <button type="button" data-map="reset" title="Torna alla vista completa">Centra</button>
            <button type="button" data-map="expand" aria-pressed="false" title="Espandi la mappa">Espandi ⛶</button>
          </div>
        </div>
        <div class="map-viewport" id="map-viewport" tabindex="0" aria-label="Mappa di Thespira. Usa i pulsanti per ingrandire, le frecce per spostarti oppure trascina con il mouse o con il dito.">
          <img src="assets/mappa-thespira.jpg" id="map-image" alt="Mappa illustrata del continente di Thespira con le regioni, i fiumi e le principali località" draggable="false">
        </div>
      </div>
      <p class="map-help"><strong>Come esplorarla:</strong> usa + e − oppure la rotella del mouse per ingrandire, trascina per spostarti. Da smartphone usa due dita per lo zoom. Premi <strong>Centra</strong> per tornare alla vista generale.</p>
      <div class="info-banner"><strong>Una mappa, tante storie.</strong> Questa prima versione è una carta consultabile. In futuro potremo aggiungere segnaposti cliccabili collegati alle schede dei luoghi, mantenendo nascosti eventuali contenuti ancora sconosciuti alla compagnia.</div>
      <h2 class="section-title rule-title">Esplora le voci dell'Atlante</h2>
      <div class="related"><a href="#/luoghi">Tutti i luoghi documentati ↗</a><a href="#/cronologia">Cronologia del viaggio ↗</a></div>
      <div class="ornament" aria-hidden="true">✦ ⟡ ✦</div>`);
  }
  function renderNotFound() {return page(`${title("Pagina non trovata","Questa voce non è disponibile","Il contenuto potrebbe essere ancora in preparazione.")}<a class="button-link" href="#/">Torna alla panoramica →</a>`);}
  function normalizedHash() {const raw=location.hash.slice(1)||"/";return raw.replace(/^\/+/,"/").split("?")[0].split("#")[0];}
  function navigate() {
    if (destroyMapViewer) {destroyMapViewer();destroyMapViewer = null;}
    const route=normalizedHash();let html;
    if(route==="/")html=renderHome();
    else if(route==="/cronologia")html=renderTimeline();
    else if(route==="/mappa")html=renderMap();
    else if(route==="/cronologia/manna")html=renderChapter("manna");
    else if(route==="/cronologia/reietti")html=renderChapter("reietti");
    else if(route==="/cronologia/lantrelle")html=renderChapter("lantrelle");
    else if(route==="/cronologia/brugheroccia")html=renderChapter("brugheroccia");
    else if(route==="/cronologia/obsydra")html=renderChapter("obsydra");
    else {const seg=route.split("/").filter(Boolean);const section=sections.find(x=>x.path===seg[0]);html=section?(seg.length===1?renderCollection(section):seg.length===2?renderEntry(section,seg[1]):renderNotFound()):renderNotFound();}
    main.innerHTML=html;
    if (route === "/mappa") destroyMapViewer = initThespiraMap(main);
    const navActive=route==="/"?"#/":route.startsWith("/cronologia/")?`#${route}`:"#/"+(route.split("/")[1]||"");
    document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.getAttribute("href")===navActive));
    document.title=(route==="/"?"Cronache di Thespira":(main.querySelector("h1")?.textContent||"Cronache")+" — Cronache di Thespira");
    if (!route.includes("/cronologia/manna")) window.scrollTo(0,0);
    closeMenu();
  }
  function closeMenu(){sidebar.classList.remove("open");shade.hidden=true;menu.setAttribute("aria-expanded","false");}
  menu.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");shade.hidden=!open;menu.setAttribute("aria-expanded",String(open));});
  shade.addEventListener("click",closeMenu);
  function allSearchEntries() {return [
    ...data.chapters.filter(x=>x.published).map(x=>({name:x.title,type:"Capitolo",href:`#/cronologia/${x.slug}`,description:x.description})),
    {name:"Mappa di Thespira",type:"Atlante",href:"#/mappa",description:"Carta geografica illustrata, ingrandibile e navigabile: Nemorae, Surturheim, Aurelia, Velmora e Ashamir."},
    ...sections.flatMap(s=>data[s.collection].map(x=>({name:x.name,type:s.title,href:linkFor(s,x),description:x.intro,extra:[...(x.facts||[]),...(x.questions||[])].join(" ")})))
  ];}
  function showSearch() {backdrop.hidden=false;searchInput.value="";showResults("");searchInput.focus();document.body.style.overflow="hidden";}
  function hideSearch() {backdrop.hidden=true;document.body.style.overflow="";document.getElementById("search-toggle").focus();}
  function showResults(query) {const term=query.trim().toLocaleLowerCase("it");const matches=allSearchEntries().filter(x=>!term||(x.name+" "+x.type+" "+x.description+" "+(x.extra||"")).toLocaleLowerCase("it").includes(term));
    searchResults.innerHTML=matches.length?matches.slice(0,20).map(x=>`<a class="search-result-link" href="${x.href}"><strong>${esc(x.name)}</strong><small>${esc(x.type)} · ${esc(x.description)}</small></a>`).join(""):`<p class="empty-note">Nessuna voce pubblicata corrisponde alla ricerca.</p>`;
  }
  document.getElementById("search-toggle").addEventListener("click",showSearch);
  document.getElementById("search-close").addEventListener("click",hideSearch);
  searchInput.addEventListener("input",()=>showResults(searchInput.value));
  searchResults.addEventListener("click",e=>{if(e.target.closest("a"))hideSearch();});
  backdrop.addEventListener("click",e=>{if(e.target===backdrop)hideSearch();});
  document.addEventListener("keydown",e=>{
    if(e.key==="Escape"){if(!backdrop.hidden)hideSearch();else closeMenu();}
    else if(e.key==="/"&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^(INPUT|TEXTAREA)$/.test(document.activeElement.tagName)){e.preventDefault();if(backdrop.hidden)showSearch();}
  });
  // Hash-based route avoids server rewrites and works on GitHub project Pages.
  window.addEventListener("hashchange",()=>{navigate();window.scrollTo({top:0,behavior:"instant"});});
  // TOC uses a normal fragment inside the hash route: '#/cronologia/manna#la-rissa'.
  main.addEventListener("click",e=>{const el=e.target.closest("[data-toc]");if(el){e.preventDefault();const target=document.getElementById(el.dataset.toc);if(target)target.scrollIntoView({behavior:"smooth",block:"start"});}});
  navigate();
})();
