/* CRONACHE DI THESPIRA — CONTENUTI PUBBLICI
 * SOLO informazioni che la compagnia conosce. Mai inserire materiale del DM.
 * Per aggiungere un capitolo, pubblicarlo qui e aggiornare published: true.
 */
const CHRONICLES = {
  updated: "09 ottobre 2026 · aggiornato con il Capitolo VI",
  current: {
    place: "Ebavurage · Le Due Lanterne",
    subtitle: "A metà giornata, la compagnia esamina l'equipaggiamento della bottega. Nessun acquisto è ancora stato effettuato.",
    next: "Alina ha chiesto agli avventurieri di raggiungere la vecchia fattoria Bellier la notte seguente."
  },
  chapters: [
    {number:"I", slug:"manna", title:"Manna e Lilith-Zetto", region:"Nemorae", published:true, description:"La nascita della compagnia, i rapimenti nelle foreste e una pagina indecifrabile."},
    {number:"II", slug:"reietti", title:"L’ordine di Selese Arco", region:"Nemorae", published:true, description:"L’ordine del Settenario Aureo, l’incontro con Nero e la scelta di difendere i reietti."},
    {number:"III", slug:"lantrelle", title:"Il rapporto di Lantrelle", region:"Nemorae", published:true, description:"La menzogna di Tomato, l'armatura di Derrick, l'intervento di Cato Mirel e la nuova missione."},
    {number:"IV", slug:"brugheroccia", title:"Il Babau di Brugheroccia", region:"Surturheim", published:true, description:"Una richiesta d’aiuto lungo il Lirion, un demone nelle miniere e l’ospitalità del Crucitti."},
    {number:"V", slug:"obsydra", title:"Obsydra e il Vecchio Paladino Oscuro", region:"Surturheim", published:true, description:"Una città di pietra e vapore, la ricerca di Teren Voss, due pagine misteriose e il giuramento di un guerriero antico."},
    {number:"VI", slug:"paludi", title:"Le paludi di Nemorae", region:"Nemorae", published:true, description:"Il ritorno da Brugheroccia, i canyons del Surturheim e lo scontro con la gang di don Batraci."},
    {number:"VII", slug:"roncenoir", title:"Roncenoir e le Grandi Fauci", region:"Nemorae", published:true, description:"Giotis Pana, il racconto di Lethraën, la caccia alle Grandi Fauci e la pista della biblioteca di Heliara."},
    {number:"VIII", slug:"gola", title:"La strada per Heliara", region:"Nemorae", published:false, description:"Il viaggio e l'incontro con Mercer Berus."},
    {number:"IX", slug:"ebavurage", title:"Ebavurage", region:"Nemorae", published:false, description:"Il borgo, il bestiame massacrato e i sospetti dei suoi abitanti."}
  ],
  people: [
    {slug:"wilhelm-codroipo", name:"Wilhelm Codroipo", role:"Locandiere", where:"Manna", intro:"Gestisce il Cervo Sonnacchioso, la locanda in cui cinque futuri compagni hanno incrociato le proprie strade.", facts:["Durante una serata al Cervo Sonnacchioso, un gruppo di avventori rivolge offese transfobiche a Wilhelm.","Akros, Baldur, Derrick, Orgen e Tomato intervengono nella rissa e allontanano gli aggressori.","Wilhelm ringrazia i cinque offrendo vitto e alloggio."], relations:["manna","cervo-sonnacchioso"]},
    {slug:"margravio", name:"Il Margravio di Manna", role:"Amministratore del villaggio", where:"Manna", intro:"Un ometto pomposo che si presenta come Margravio e si occupa dell'amministrazione di Manna.", facts:["Affida ai sei avventurieri il compito di fermare Lilith-Zetto.","Riferisce che una bambina è stata rapita e che altri bambini scomparsi non sono mai tornati."], relations:["manna"]},
    {slug:"vecchio", name:"Il vecchio della foresta", role:"Identità sconosciuta", where:"Foreste di Nemorae", intro:"Uno sconosciuto dall'aspetto stanco, incontrato durante la ricerca di Lilith-Zetto.", facts:["Dissolve due spaventapasseri animati semplicemente posando loro una mano sulla schiena.","Ospita la compagnia nella propria baracca e fornisce indicazioni per raggiungere la megera.","Dopo la scomparsa lascia a Brann un messaggio: sa del furto della pagina, ma vuole che il kenku la conservi."], relations:["baracca","prima-pagina"]},
    {slug:"lilith-zetto", name:"Lilith-Zetto", role:"Megera Verde · sconfitta", where:"Foreste di Nemorae", intro:"Una Megera Verde responsabile di ripetuti rapimenti di bambini nelle vicinanze di Manna.", facts:["Gli avventurieri la raggiungono nel suo antro dopo aver combattuto alcuni spaventapasseri animati.","La compagnia riesce a sconfiggerla.","La bambina rapita più di recente non può essere salvata."], relations:["antro-megera","manna"]},
    {slug:"selese-arco", name:"Magistra Selese Arco", image:"assets/selese-arco-portrait.png", role:"Magistra · Settenario Aureo", where:"Manna · Cervo Sonnacchioso", intro:"Esponente del Settenario Aureo, il gruppo d’élite della Chiesa di Amaunator. La compagnia la incontra dopo essere tornata da Lilith-Zetto.", facts:["Raggiunge il Cervo Sonnacchioso accompagnata da quattro guardie, indossando abiti bianchi, oro e blu.","Accusa il gruppo di avere intralciato un’indagine della Chiesa nelle Foreste di Nemorae, che comprendeva anche le attività di Lilith-Zetto.","Ordina agli avventurieri di rintracciare e sterminare un gruppo di nomadi provenienti da Heliara, che presenta come traditori della Chiesa.","Chiede loro di fare rapporto a Lantrelle. La compagnia finirà per schierarsi dalla parte dei perseguitati.","A Lantrelle riconosce l'armatura di un ufficiale della Chiesa indossata da Derrick, compromettendo il falso rapporto di Tomato.","Cato Mirel ipotizza davanti a lei un secondo scopo nell'invio di due ufficiali considerati ‘impuri’ per una presunta relazione omosessuale; Selese si irrigidisce ma non insiste."], relations:["cervo-sonnacchioso","manna","accampamento-reietti","lantrelle","cato-mirel"]},
    {slug:"nero", name:"Nero", role:"Viaggiatore misterioso", where:"A nord di Manna", intro:"Uno sconosciuto vestito di nero e con un vistoso cilindro, incontrato lungo la ricerca dell’accampamento dei reietti.", facts:["La compagnia lo salva da un androsfinge.","Per ringraziare gli avventurieri dona loro quattro Anelli del Camminare sull’Acqua."], relations:["anelli-acqua","foreste-nemorae"]},
    {slug:"arel", name:"Arel", role:"Bambino dell’accampamento", where:"Accampamento dei reietti", intro:"Un bambino soccorso dagli avventurieri lungo il viaggio a nord di Manna.", facts:["Fa parte dell’accampamento cercato dalla compagnia e, senza comprenderne le intenzioni iniziali, ve la conduce.","Viene ucciso durante l’assalto di uomini con le insegne della Chiesa di Amaunator."], relations:["accampamento-reietti"]},
    {slug:"brannor", name:"Brannor", role:"Reietto · ex funzionario della Chiesa", where:"Accampamento dei reietti", intro:"Uno degli uomini dell’accampamento che offre agli avventurieri cena e ospitalità.", facts:["Accoglie la compagnia per la sera e la notte.","Il mattino dopo l’assalto riferisce che i reietti erano stati funzionari della Chiesa di Amaunator.","Secondo il suo racconto, il fratello è stato assassinato a Heliara dopo avergli confidato che la Chiesa cercava segretamente un antico diario.","Sostiene che Selese Arco sia stata inviata per eliminare eventuali testimoni di questa ricerca."], relations:["accampamento-reietti","antico-diario"]},
    {slug:"cato-mirel", name:"Magistro Cato Mirel", image:"assets/cato-mirel-portrait.png", role:"Magistro · Settenario Aureo", where:"Lantrelle", intro:"Un giovanissimo Magistro dai capelli biondi, allegro e apparentemente ingenuo; dietro i modi cordiali mostra un intuito particolarmente acuto.", facts:["La compagnia lo incontra mentre conversa con Selese Arco a Lantrelle.","Interviene quando Selese scopre la menzogna degli avventurieri, grazie anche all'armatura di un ufficiale della Chiesa indossata da Derrick.","Suggerisce che Selese avesse inviato all'accampamento due ufficiali considerati da lei ‘impuri’ perché accusati di avere una relazione omosessuale: nella lettura di Cato, qualsiasi esito dello scontro le sarebbe convenuto.","Selese si irrigidisce, ma lascia cadere il confronto.","Propone alla compagnia un nuovo test: recuperare per lui una pagina rinvenuta nelle miniere di Obsydra.","Consiglia di visitare l'Emporio del Brambilla.","La compagnia recupera la pagina, ma decide di non tornare a consegnargliela."], relations:["lantrelle","selese-arco","pagina-obsydra","emporio-brambilla","culto-fuoco"]},
    {slug:"brambilla", name:"Il Brambilla", role:"Mercante", where:"Emporio del Brambilla", intro:"Un energico affarista brianzolo dall'accento milanese e dai modi decisi, incontrato dalla compagnia dopo il colloquio con Cato Mirel.", facts:["Gestisce l'Emporio del Brambilla, consigliato ai protagonisti da Cato.","I suoi modi sanguigni, spietatamente commerciali e caricaturali suscitano molte risate al tavolo.","La compagnia acquista alcuni generi vari, senza oggetti particolarmente rilevanti per la cronaca."], relations:["emporio-brambilla","cato-mirel"]}
    ,{slug:"don-batraci", name:"don Batraci", image:"assets/don-batraci-portrait.png", role:"Capobanda grung", where:"Paludi settentrionali di Nemorae", intro:"Un grung dorato corpulento, teatrale e sprezzante, che pretende tributi e rispetto da chiunque voglia attraversare il suo ponticello nelle paludi.", facts:["Si presenta circondato da una piccola banda di grung dalla pelle colorata, che sorveglia un ponticello nelle paludi a nord di Nemorae.","Parla il Comune con poche parole scandite da un marcato accento siciliano e impone a Derrick un baciamano come gesto di sottomissione.","Pretende denaro, oggetti e rispetto per concedere il passaggio nel territorio che considera sotto il proprio controllo.","Quando Akros tenta di nascondersi durante la trattativa, interpreta il gesto come una minaccia e ordina l'attacco.","Dopo la sconfitta della sua banda, fugge gettandosi nel Lirion e promettendo vendetta."], relations:["paludi-settentrionali","ponticello-grung","anello-saltare","lirion"]}
    ,{slug:"crucitti", name:"Il Crucitti", role:"Sindaco · locandiere · imprenditore", where:"Brugheroccia", intro:"Il Crucitti, uomo sulla settantina, pelato e con un folto pizzetto, è sindaco di Brugheroccia, gestisce la locanda e dirige l’impresa di passamaneria locale.", facts:["Dai modi bruschi, energici e quasi aggressivi, è un uomo onesto e affidabile: quando dà ordini gli abitanti si affrettano a eseguirli.","Dopo la sconfitta del Babau, consegna alla compagnia una ricompensa in oro e le offre vitto e alloggio, che gli avventurieri accettano.","Racconta che Obsydra e Pyrocladion, dopo molti contrasti, sono oggi in buoni rapporti.","Attribuisce personalmente il riavvicinamento alla crescente influenza del Culto del Fuoco in entrambe le città: è una sua opinione, non un fatto confermato."], relations:["brugheroccia","miniera-brugheroccia","culto-fuoco"]}
    ,{"slug":"bram-ferrovena","name":"Bram Ferrovena","role":"Minatore · campione della birra","where":"Obsydra · Locanda del Vapore","intro":"Minatore imponente dalla barba intrecciata con frammenti di quarzo; rumoroso, competitivo e schietto.","facts":["Alla Locanda del Vapore sfida Baldur Hawthorne a una gara di bevute.","Nonostante Baldur si ubriachi, la sua determinazione conquista Bram e gli altri minatori.","Aiuta la compagnia a ricostruire le voci sulla pagina ritrovata nelle miniere e sulla scomparsa di un lavoratore.","Incontra nuovamente gli avventurieri alla locanda dopo il ritorno dalla Cava."],"relations":["locanda-vapore","dorna-spaccapietra","lerrik-occhio-storto","pagina-obsydra"]}
    ,{"slug":"dorna-spaccapietra","name":"Dorna Spaccapietra","role":"Minatrice","where":"Obsydra · Locanda del Vapore","intro":"Nana robusta e attenta, dall’indole concreta e diffidente, tra le conoscenze dei minatori della Locanda del Vapore.","facts":["È presente quando la compagnia cerca informazioni sul documento misterioso.","Assiste alla gara di bevute tra Baldur e Bram Ferrovena.","Dopo la gara si mostra, insieme agli altri minatori, più disponibile verso gli sconosciuti.","La compagnia la incontra nuovamente alla Locanda del Vapore."],"relations":["bram-ferrovena","lerrik-occhio-storto","locanda-vapore"]}
    ,{"slug":"lerrik-occhio-storto","name":"Lerrik «Occhio Storto»","role":"Minatore","where":"Obsydra · Locanda del Vapore","intro":"Minatore magro e superstizioso, con un occhio velato e un atteggiamento inquieto.","facts":["Frequentatore della Locanda del Vapore, è tra i minatori interpellati sulla pagina misteriosa.","Assiste alla gara di bevute che consente a Baldur di guadagnare la fiducia degli avventori.","È nuovamente presente alla locanda quando la compagnia vi ritrova Sefra «Tre-Dita»."],"relations":["bram-ferrovena","dorna-spaccapietra","locanda-vapore"]}
    ,{"slug":"orisel-tharn","name":"Dama Orisel Tharn","role":"Direttrice della Biblioteca Olivetti","where":"Obsydra","intro":"Anziana nana dal carattere severo, responsabile della Biblioteca Olivetti, nella quale era stata custodita la misteriosa pagina.","facts":["Conferma che la pagina ritrovata nelle miniere era stata consegnata alla Biblioteca.","Le domande della compagnia la rendono visibilmente nervosa e la inducono a raccontare alcune visite precedenti.","Riferisce dell’interesse di un giovane biondo della Chiesa di Amaunator e di un uomo che aveva reclamato il reperto.","Rivela che la pagina è stata rubata e fornisce agli avventurieri il recapito lasciato da Mira Voss."],"relations":["biblioteca-olivetti","mira-voss","pagina-obsydra"]}
    ,{"slug":"teren-voss","name":"Teren Voss","role":"Minatore · scopritore della pagina","where":"Obsydra","intro":"Minatore esperto, frustrato dalla propria posizione e desideroso di dimostrare il proprio valore agli abitanti di Obsydra.","facts":["Trova una pagina insolita durante il lavoro; il capoturno gliela sottrae per consegnarla alla Biblioteca.","Chiede a Sefra «Tre-Dita» di recuperarla e spera di ricavarne prestigio o guadagno.","Lascia il documento alla moglie Mira e scende nella Cava in cerca di reperti simili.","Viene trovato in buone condizioni dagli avventurieri e, dopo il crollo, li guida fuori attraverso cunicoli e gallerie attive.","Torna a casa dalla moglie, che consegna la pagina alla compagnia."],"relations":["mira-voss","sefra-tre-dita","cava-obsydra","pagina-obsydra"]}
    ,{"slug":"mira-voss","name":"Mira Voss","role":"Sarta · moglie di Teren Voss","where":"Obsydra","intro":"Sarta di Obsydra, molto bella e profondamente legata al marito Teren, della cui scomparsa è sinceramente preoccupata.","facts":["Racconta alla compagnia del ritrovamento della pagina da parte di Teren e della sua successiva scomparsa.","Inizialmente tace che Teren le abbia affidato la pagina prima di tornare nella Cava.","Spiega di averlo nascosto per paura che gli avventurieri, ottenuto il reperto, rinunciassero a cercare suo marito.","Dopo il ritorno di Teren, consegna la pagina alla compagnia in segno di riconoscenza.","Orgen rimane presso l’abitazione dei Voss mentre gli altri cinque avventurieri partono per Roncenoir."],"relations":["teren-voss","pagina-obsydra","obsydra"]}
    ,{"slug":"sefra-tre-dita","name":"Sefra «Tre-Dita»","role":"Ricettatrice · mercato nero","where":"Obsydra","intro":"Mezzelfa trasandata, con il viso triangolare e olivastro, occhi giallastri, capelli radi e spettinati e un ghigno allusivo; porta una cappa viola scuro.","facts":["Alla mano sinistra conserva soltanto pollice, indice e medio.","Ammette di aver sottratto la pagina alla Biblioteca Olivetti su richiesta di Teren Voss.","Ritiene che il documento non abbia valore commerciale, benché sia insolito e apparentemente indistruttibile.","Incontra nuovamente la compagnia alla Locanda del Vapore dopo il ritorno dalla Cava.","Spinta dalla curiosità, rinuncia a cercare un guadagno e indirizza il gruppo verso Giotis Pana, un vecchio mentore studioso di antichità che vive a Roncenoir."],"relations":["teren-voss","biblioteca-olivetti","locanda-vapore","pagina-obsydra","giotis-pana","roncenoir"]}
    ,{"slug":"rurik-pietracorta","name":"Rurik Pietracorta","role":"Ex minatore · guida","where":"Obsydra · Miniere","intro":"Anziano minatore che conosce le gallerie più antiche di Obsydra e il percorso verso la Cava.","facts":["Accompagna la compagnia attraverso gli scavi fino all’imboccatura della Cava.","Conoscendo i rischi delle profondità, rifiuta di procedere oltre e lascia che gli avventurieri proseguano da soli."],"relations":["miniere-obsydra","cava-obsydra"]}
    ,{"slug":"paladino-oscuro","name":"Il Vecchio Paladino Oscuro","role":"Guerriero misterioso · deceduto","where":"Obsydra · la Cava","intro":"Figura dall’aspetto elfico, alta e possente, dalla pelle pallida, i capelli scuri irregolari e un’armatura pesante, annerita dal tempo e dalla polvere.","facts":["Ha il volto allungato, occhi infossati e quasi vuoti, bocca esangue e rughe profonde: appare antico più che anziano.","Attacca frontalmente gli avventurieri nelle profondità della Cava.","Durante lo scontro osserva Derrick con incredulità, come se lo riconoscesse.","Morente, chiama Derrick per nome, lo accusa di aver tradito Aurel e lo supplica di non consegnare la pagina alla Chiesa.","Dona a Derrick la Spada lunga del Giuramento e muore con un accenno di sorriso."],"questions":["Chi era questo guerriero?","Perché riconosceva Derrick?","Chi è Aurel e che cosa significa l’accusa di tradimento?"],"relations":["cava-obsydra","spada-giuramento","pagina-obsydra"]},
    {"slug": "giotis-pana", "name": "Giotis Pana", "role": "Archeologo e studioso elfo", "where": "Roncenoir", "intro": "Anziano elfo archeologo dagli occhiali rotondi e dai capelli grigi disordinati: eccentrico, appassionato, assai competente e animato da un entusiasmo contagioso.", "facts": ["È giunto a Roncenoir circa vent’anni prima per studiarne gli abitanti; il fascino del luogo ha reso sempre più difficile l’idea di lasciarlo.", "Vive in una capanna ricca di libri, appunti e strumenti, insolita in una comunità che preferisce adattarsi alla foresta.", "Racconta di aver accolto Sefra «Tre-Dita» quando viveva per strada; prova per lei un affetto paterno, comprende la sua scelta di lasciare Roncenoir e spera di rivederla.", "Esamina inizialmente una sola delle due pagine: riconosce un reperto antichissimo, forse legato a Heliara, ma non ne comprende i simboli.", "Dopo la caccia alle Grandi Fauci esamina anche la seconda pagina e suggerisce di cercare scritture simili tra i libri più antichi della biblioteca di Heliara.", "L’interesse per le pagine lo convince ad accompagnare i cinque avventurieri alla capitale."], "relations": ["roncenoir", "sefra-tre-dita", "prima-pagina", "pagina-obsydra", "acque-profonde", "lethraen"]},
    {"slug": "lethraen", "name": "Lethraën", "role": "Anziano riferimento della comunità", "where": "Roncenoir", "intro": "Elfo di oltre ottocento anni, cieco e sordo, autorevole per esperienza più che per carica: comunica con una voce telepatica profonda.", "facts": ["Siede su uno scranno ricavato dalle radici e dai tronchi intrecciati di un ficus immenso, assistito da un giovane elfo.", "La sua pelle ricorda la corteccia di un albero antico, mentre il braccio sinistro appare pietrificato: Lethraën lo collega alla Grande Piaga.", "Racconta che circa ottocento anni prima l’Abisso si riversò sul Surturheim, portando demoni e una piaga capace di corrompere ciò che toccava.", "Secondo la sua testimonianza, i kenku nomadi fuggiti in Nemorae in cerca di rifugio furono massacrati dagli elfi e dalle creature della foresta; Lethraën ne porta ancora il rimorso.", "Commosso dalla presenza di Brann, gli accarezza una guancia e gli chiede perdono per le violenze del passato.", "Chiede agli avventurieri di abbattere le Grandi Fauci, un predatore che ormai minaccia animali e abitanti e compromette l’equilibrio della zona.", "Dopo la vittoria consegna alla compagnia la Caraffa dell’Acqua Eterna e la saluta prima del viaggio per Heliara."], "relations": ["roncenoir", "grande-piaga", "grandi-fauci", "acque-profonde", "caraffa-acqua-eterna"]}
  ],
  places: [
    {slug:"manna", name:"Manna", type:"Villaggio", region:"Nemorae", intro:"Insediamento nelle Foreste di Nemorae, dove si sono incontrati i sei membri della compagnia.", facts:["Ospita la locanda del Cervo Sonnacchioso.","È amministrata da un individuo che si presenta come Margravio di Manna.","I suoi abitanti hanno sofferto per i rapimenti compiuti da Lilith-Zetto."], relations:["cervo-sonnacchioso","foreste-nemorae"]},
    {slug:"cervo-sonnacchioso", name:"Il Cervo Sonnacchioso", type:"Locanda", region:"Manna", intro:"Locanda di Wilhelm Codroipo, teatro della rissa che ha riunito i primi cinque avventurieri.", facts:["Tomato vi suona la baggopipa per guadagnarsi vitto e alloggio.","Gli avventori che insultano Wilhelm e Tomato vengono messi alla porta.","Wilhelm offre vitto e alloggio ai cinque che sono intervenuti."], relations:["manna"]},
    {slug:"foreste-nemorae", name:"Foreste di Nemorae", type:"Regione boschiva", region:"Nemorae", intro:"Le vaste foreste attraversate dalla compagnia durante le prime avventure.", facts:["Brann incontra un branco di lupi dopo aver rubato la baggopipa di Tomato.","Gli avventurieri combattono gli spaventapasseri animati durante la ricerca di Lilith-Zetto.","La baracca di un vecchio misterioso e l'antro della megera si trovano al loro interno."], relations:["baracca","antro-megera"]},
    {slug:"baracca", name:"La baracca del vecchio", type:"Abitazione isolata", region:"Foreste di Nemorae", intro:"Rifugio dello sconosciuto che aiuta la compagnia contro gli spaventapasseri.", facts:["La compagnia vi trascorre una notte.","Brann vi trova e sottrae una pagina coperta di simboli incomprensibili.","Al ritorno, il vecchio non c'è più; rimane un messaggio destinato a Brann."], relations:["foreste-nemorae","prima-pagina"]},
    {slug:"antro-megera", name:"L'antro di Lilith-Zetto", type:"Nascondiglio", region:"Foreste di Nemorae", intro:"Il rifugio della Megera Verde, raggiunto dalla compagnia seguendo le indicazioni del vecchio.", facts:["Qui la compagnia affronta e sconfigge Lilith-Zetto.","La bambina rapita non può essere salvata."], relations:["foreste-nemorae"]},
    {slug:"accampamento-reietti", name:"L’accampamento dei reietti", type:"Accampamento itinerante", region:"A nord di Manna · Nemorae", intro:"Accampamento mobile di un gruppo di persone originarie di Heliara, descritte da Selese Arco come pericolosi traditori della Chiesa.", facts:["Arel, un bambino salvato dagli avventurieri, conduce il gruppo all’accampamento.","Brannor offre agli avventurieri cena e ospitalità.","Durante la cena uomini con le insegne della Chiesa attaccano il campo e uccidono Arel.","La compagnia si schiera con gli abitanti dell’accampamento e sconfigge gli assalitori."], relations:["arel","brannor","selese-arco"]},
    {slug:"lantrelle", name:"Lantrelle", type:"Avamposto commerciale", region:"Nemorae", intro:"Avamposto commerciale a nord-est di Manna, al riparo dall'influenza diretta della Chiesa grazie alla protezione della Regina Veyra.", facts:["Selese Arco vi attende il rapporto sulla missione contro i reietti.","La compagnia incontra qui Magistro Cato Mirel.","Il falso rapporto di Tomato viene compromesso dall'armatura di un ufficiale della Chiesa indossata da Derrick.","Cato interrompe l'inasprimento del confronto e propone una missione a Obsydra."], relations:["selese-arco","cato-mirel","pagina-obsydra"]},
    {slug:"emporio-brambilla", name:"Emporio del Brambilla", type:"Emporio per avventurieri", region:"Tappa successiva a Lantrelle", intro:"Bottega raccomandata da Cato Mirel per gli approvvigionamenti degli avventurieri. La posizione precisa non è ancora documentata nella cronaca.", facts:["Il mercante Brambilla si distingue per l'accento milanese, l'energia e la durezza nelle trattative.","La compagnia acquista generi vari, senza acquisti determinanti per l'avventura."], relations:["brambilla","cato-mirel"]}
    ,{slug:"brugheroccia", name:"Brugheroccia", type:"Borgo montano", region:"Surturheim", intro:"Piccolo e dignitoso borgo montano, isolato fra pendii spogli e scoscesi, con il grande fiume Lirion visibile nella valle sottostante.", facts:["Una miniera del luogo è teatro di fenomeni inquietanti: rumori, gelo persistente e un'oscurità anomala.","Gli avventurieri vengono fermati lungo la strada da minatori preoccupati per un compagno rimasto sottoterra.","Dopo la sconfitta del Babau, gli abitanti mostrano una riconoscenza sincera, senza organizzare festeggiamenti.","Il Crucitti, sindaco e locandiere, ricompensa la compagnia con oro, vitto e alloggio; gli avventurieri pernottano nel borgo."], relations:["crucitti","miniera-brugheroccia","lirion","babau-brugheroccia"]},
    {slug:"miniera-brugheroccia", name:"La miniera di Brugheroccia", type:"Miniera", region:"Brugheroccia · Surturheim", intro:"Complesso sotterraneo con alcune diramazioni, nel quale un minatore è rimasto mentre si manifestavano fenomeni inspiegabili.", facts:["I lavoratori riferiscono rumori, gelo persistente e un buio eccezionalmente fitto.","Un crollo impone una breve deviazione e la compagnia affronta alcuni Mephit di terra.","In una camera sotterranea il gruppo scopre il corpo smembrato del minatore disperso.","Dall'oscurità emerge un Babau che sorprende Baldur; la compagnia affronta e sconfigge il demone."], relations:["brugheroccia","babau-brugheroccia"]},
    {slug:"lirion", name:"Fiume Lirion", type:"Fiume", region:"Nemorae · Surturheim", intro:"Grande corso d'acqua costeggiato dalla strada che conduce la compagnia fuori dalle Foreste di Nemorae e verso il Surturheim.", facts:["Il viaggio per Obsydra segue per un tratto il corso del fiume.","Il Lirion è visibile dalla valle sottostante Brugheroccia."], relations:["brugheroccia","foreste-nemorae"]}
    ,{"slug":"paludi-settentrionali","name":"Paludi settentrionali di Nemorae","type":"Zona paludosa","region":"Nemorae","intro":"Un tratto di paludi attraversato dalla compagnia sulla via per Roncenoir: alberi enormi, acqua stagnante, insetti e un odore costante di marcescenza.","facts":["Gli alberi hanno forme gigantesche e quasi acquatiche, tra pozze limacciose e ristagni d'acqua.","I sentieri sono poco definiti e difficili da seguire: Akros guida il gruppo nell'attraversamento.","Qui la compagnia incontra una banda di grung guidata da don Batraci."],"relations":["foreste-nemorae","don-batraci","ponticello-grung","roncenoir"]}
    ,{"slug":"ponticello-grung","name":"Il ponticello dei grung","type":"Passaggio sorvegliato","region":"Paludi settentrionali di Nemorae","intro":"Un piccolo ponte di legno sorvegliato da una banda di grung che pretende pedaggi dai viaggiatori.","facts":["Davanti al ponticello la compagnia incontra per la prima volta quattro grung dalla pelle colorata intenti a scherzare tra loro.","Poco dopo sopraggiunge don Batraci, un grung dorato che si comporta come il signore del luogo.","Il tentativo di trattativa fallisce e il passaggio diventa teatro dello scontro con la banda."],"relations":["paludi-settentrionali","don-batraci"]}
    ,{"slug":"obsydra","name":"Obsydra","type":"Grande città-stato mineraria","region":"Surturheim","intro":"Imponente città industriale edificata su pendii scoscesi, attraversata dal fiume Lirion, con edifici di pietra scura e un incessante rumore di martelli e meccanismi.","facts":["Mura massicce, ponti e torri di pietra collegano più livelli urbani incastonati nella montagna.","Vapori, fumo, attività estrattive e officine caratterizzano la città, caotica ma industrialmente progredita.","La compagnia entra dal Varco della Scoria superando un ordinario controllo e alloggia al Cervo in Dormiveglia.","Nelle sue miniere Teren Voss trova una pagina misteriosa, successivamente recuperata dalla compagnia.","Al Varco della Scoria sono visibili simboli del Culto del Fuoco, ma la compagnia non sperimenta ostilità verso Amaunator."],"relations":["lirion","varco-scoria","cervo-dormiveglia","locanda-vapore","biblioteca-olivetti","miniere-obsydra","culto-fuoco"]}
    ,{"slug":"varco-scoria","name":"Varco della Scoria","type":"Porta monumentale","region":"Obsydra · Surturheim","intro":"Ingresso principale di Obsydra, formato da un grande arco di basalto e fiancheggiato da statue di guerrieri con elmo e martello.","facts":["Un’insegna metallica reca il motto «Il fuoco purifica. Il fuoco forgia».","La compagnia viene sottoposta a un controllo ordinario, anche alla presenza di un accolito del Culto del Fuoco.","Le guardie non mostrano particolare ostilità agli avventurieri."],"relations":["obsydra","culto-fuoco"]}
    ,{"slug":"cervo-dormiveglia","name":"Il Cervo in Dormiveglia","type":"Locanda","region":"Obsydra · Surturheim","intro":"Locanda di Obsydra nella quale la compagnia prende alloggio durante le indagini sulla pagina.","facts":["Gli avventurieri vi alloggiano dopo il loro arrivo in città.","È distinta dalla Locanda del Vapore, nella quale avvengono la gara di bevute e il successivo incontro con Sefra."],"relations":["obsydra","locanda-vapore"]}
    ,{"slug":"locanda-vapore","name":"Locanda del Vapore","type":"Locanda dei minatori","region":"Obsydra · Surturheim","intro":"Frequentata da lavoratori delle miniere, è il luogo della gara di bevute tra Baldur e Bram Ferrovena e del successivo incontro con Sefra.","facts":["Alla richiesta di informazioni sulla pagina, gli avventori guardano inizialmente gli avventurieri con diffidenza.","La gara di bevute tra Baldur e Bram permette alla compagnia di conquistare la fiducia dei minatori.","Bram, Dorna e Lerrik forniscono informazioni sulla reliquia e su un minatore scomparso.","Dopo il ritorno dalla Cava, la compagnia incontra qui di nuovo Sefra «Tre-Dita»."],"relations":["obsydra","bram-ferrovena","dorna-spaccapietra","lerrik-occhio-storto","sefra-tre-dita"]}
    ,{"slug":"biblioteca-olivetti","name":"Biblioteca Olivetti","type":"Biblioteca cittadina","region":"Obsydra · Surturheim","intro":"Biblioteca di Obsydra che custodisce per qualche tempo la pagina ritrovata nelle miniere prima della sua sparizione.","facts":["Dama Orisel Tharn dirige l’istituzione.","Il capoturno di Teren consegna qui la pagina ritrovata dal minatore.","Dopo le visite di diverse persone interessate alla reliquia, la pagina viene trafugata da Sefra su richiesta di Teren.","Orisel informa la compagnia anche della visita di Mira Voss, preoccupata per il marito."],"relations":["obsydra","orisel-tharn","pagina-obsydra","sefra-tre-dita"]}
    ,{"slug":"miniere-obsydra","name":"Miniere di Obsydra","type":"Complesso minerario","region":"Obsydra · Surturheim","intro":"Vasto sistema di scavi, gallerie e montacarichi che alimenta l’industria della città e nel quale viene ritrovata la pagina misteriosa.","facts":["Teren Voss trova una pagina nelle miniere; il capoturno la confisca per consegnarla alla Biblioteca.","La compagnia vi entra cercando Teren, guidata da Rurik Pietracorta fino alle antiche gallerie.","Oltre le gallerie attive si apre la Cava, una voragine che incute timore ai minatori.","Dopo il crollo, Teren guida la compagnia in superficie attraverso cunicoli, gallerie attive e un montacarichi."],"relations":["obsydra","cava-obsydra","rurik-pietracorta","teren-voss"]}
    ,{"slug":"cava-obsydra","name":"La Cava","type":"Voragine sotterranea","region":"Miniere di Obsydra · Surturheim","intro":"Voragine scoperta durante l’avanzamento degli scavi: un luogo dall’aspetto antichissimo, temuto dai minatori e raggiungibile attraverso le gallerie profonde.","facts":["Teren Voss vi scende per cercare altri reperti simili alla pagina già ritrovata.","Rurik Pietracorta accompagna gli avventurieri fino all’ingresso, senza proseguire oltre.","Gli avventurieri trovano Teren in buone condizioni, ma un crollo impedisce loro di ripercorrere la strada.","Nelle profondità incontrano e sconfiggono il Vecchio Paladino Oscuro.","Teren conosce un itinerario alternativo per raggiungere le gallerie attive e uscire."],"relations":["miniere-obsydra","teren-voss","rurik-pietracorta","paladino-oscuro"]},
    {"slug": "roncenoir", "name": "Roncenoir", "type": "Insediamento forestale", "region": "Foreste settentrionali di Nemorae", "intro": "Piccolo villaggio di circa cento abitanti, privo di confini netti: gli elfi selvatici e alcuni umani si adattano alla foresta senza cercare di dominarla.", "facts": ["Gli abitanti utilizzano prevalentemente gli elementi naturali esistenti invece di creare grandi costruzioni artificiali.", "La comunità comprende soprattutto elfi selvatici, del tutto a proprio agio nell’ambiente, e alcuni umani che tentano di seguirne le abitudini.", "La comunicazione è spesso non verbale e l’accoglienza degli stranieri non è né calorosa né ostile.", "Un enorme ficus al centro dell’insediamento ospita lo scranno di Lethraën, la più autorevole figura della comunità.", "La dimora dello studioso Giotis Pana, con libri e mobili convenzionali, costituisce un’eccezione alle abitudini del villaggio.", "Dopo la sconfitta delle Grandi Fauci, gli abitanti guardano gli avventurieri con un rispetto nuovo, senza organizzare festeggiamenti."], "relations": ["paludi-settentrionali", "giotis-pana", "lethraen", "acque-profonde"]},
    {"slug": "acque-profonde", "name": "Le Acque Profonde", "type": "Specchio d’acqua paludoso", "region": "Nemorae · presso Roncenoir", "intro": "Ampio specchio d’acqua, uno dei rari luoghi scoperti della foresta, circondato da alberi: alterna punti guadabili a zone spaventosamente profonde.", "facts": ["Lethraën vi indirizza la compagnia per affrontare il predatore soprannominato le Grandi Fauci.", "Gli avventurieri utilizzano una capra viva come esca ai margini dell’acqua.", "Alla stessa esca accorrono un coccodrillo gigante e altri due coccodrilli, che la compagnia affronta e abbatte."], "relations": ["roncenoir", "grandi-fauci", "lethraen"]}
  ],
  discoveries: [
    {slug:"prima-pagina", name:"La prima pagina", type:"Oggetto misterioso", state:"Origine sconosciuta", intro:"Una pagina ricoperta di segni incomprensibili, trovata da Brann nella baracca del vecchio.", facts:["Brann se ne impossessa durante la notte trascorsa nella baracca.","Il vecchio sa del furto e, nel messaggio lasciato prima di scomparire, chiede che sia Brann a conservarla.","Al termine della prima avventura nessuno della compagnia è in grado di interpretarne i simboli.","Una seconda pagina recuperata a Obsydra presenta caratteristiche materiali analoghe ma simboli differenti; le due sembrano indistruttibili."], questions:["Chi ha scritto la pagina?","Che cosa significano i simboli?","Perché il vecchio ha deciso di lasciarla a Brann?"], relations:["baracca","vecchio","pagina-obsydra"]},
    {slug:"anelli-acqua", name:"Anelli del Camminare sull’Acqua", type:"Oggetti magici", state:"Quattro anelli ricevuti", intro:"Quattro anelli consegnati da Nero agli avventurieri come ringraziamento per averlo salvato da un androsfinge.", facts:["Nero dona alla compagnia quattro Anelli del Camminare sull’Acqua.","L’incontro avviene durante il viaggio alla ricerca dei reietti a nord di Manna."], relations:["nero"]},
    {slug:"antico-diario", name:"Il diario ricercato dalla Chiesa", type:"Testimonianza e mistero", state:"Notizia riferita da Brannor", intro:"Secondo Brannor, la Chiesa di Amaunator cerca un antico diario nel massimo segreto.", facts:["Brannor sostiene che suo fratello gli abbia parlato dell’operazione a Heliara.","Riferisce che il fratello è stato ucciso poco dopo quella confidenza.","Brannor collega a questa scoperta la persecuzione degli ex funzionari della Chiesa fuggiti dall’accampamento."], questions:["Di quale diario si tratta?","Perché la Chiesa lo cerca?","Esiste un legame con la pagina trovata da Brann?"], relations:["brannor","prima-pagina"]},
    {slug:"pagina-obsydra", name:"La seconda pagina · Obsydra", type:"Oggetto misterioso", state:"In possesso della compagnia · non consegnata alla Chiesa", intro:"Pagina rinvenuta da Teren Voss nelle miniere di Obsydra. Cato Mirel ne richiede il recupero per conto della Chiesa, ma dopo averla ottenuta la compagnia decide di conservarla.", facts:["Teren la rinviene nelle miniere e il suo capoturno la porta alla Biblioteca Olivetti.","Su richiesta di Teren, Sefra «Tre-Dita» sottrae il documento alla Biblioteca; Teren lo affida poi a Mira prima di tornare nella Cava.","Mira tace di averla per assicurarsi che gli avventurieri continuino a cercare suo marito; quando Teren è salvo, la consegna alla compagnia.","La pagina e quella trovata da Brann condividono caratteristiche materiali straordinarie, ma i segni riportati sono diversi.","Entrambe resistono ai tentativi degli avventurieri di danneggiarle.","La compagnia decide di non riportare la pagina a Cato Mirel e segue la pista di Giotis Pana, suggerita da Sefra.","A Roncenoir Giotis esamina inizialmente una pagina e, dopo la caccia alle Grandi Fauci, confronta anche la seconda; suggerisce di cercare scritture affini nella biblioteca di Heliara."], questions:["Chi ha scritto le due pagine?","Qual è il loro significato?","Perché la Chiesa desidera recuperarle?"], relations:["cato-mirel","prima-pagina","biblioteca-olivetti","teren-voss","mira-voss","sefra-tre-dita","giotis-pana"]},
    {slug:"armatura-ufficiale", name:"L'armatura dell'ufficiale", type:"Equipaggiamento recuperato", state:"Indossata da Derrick a Lantrelle", intro:"Armatura appartenuta a un ufficiale della Chiesa caduto nello scontro all'accampamento dei reietti.", facts:["Derrick recupera e indossa l'armatura dopo lo scontro.","A Lantrelle Selese la riconosce mentre Tomato tenta di sostenere un falso rapporto.","La scoperta fa precipitare il confronto con la Magistra."], relations:["selese-arco","lantrelle","accampamento-reietti"]}
    ,{slug:"babau-brugheroccia", name:"Il Babau di Brugheroccia", type:"Creatura abissale", state:"Sconfitto nella miniera", intro:"Demone abissale riconosciuto dalla compagnia nelle profondità della miniera di Brugheroccia. Creature simili sono solitamente legate alle leggende di Thespira.", facts:["La sua presenza è accompagnata da un'oscurità anomala e da una sensazione di gelo persistente.","Nella camera in cui si nasconde si trova il corpo smembrato di un minatore.","Baldur è colpito a sorpresa dopo essersi avvicinato al corpo; il combattimento è impegnativo, ma la compagnia uccide il demone.","L'incontro richiama gli ammonimenti del misterioso vecchio della foresta, senza stabilire che i due episodi siano collegati."], questions:["Come è arrivato un demone abissale nella miniera?","La sua presenza è un caso isolato?"], relations:["miniera-brugheroccia","vecchio","brugheroccia"]},
    {slug:"culto-fuoco", name:"Il Culto del Fuoco nel Surturheim", type:"Culto religioso · notizie raccolte", state:"Informazioni riferite da Cato Mirel e dal Crucitti", intro:"Culto radicato nel Surturheim, al quale secondo quanto riferito alla compagnia sono particolarmente legate Obsydra e Pyrocladion.", facts:["Cato Mirel afferma che la devozione locale al Culto del Fuoco contribuisce alla diffidenza verso la Chiesa di Amaunator.","Il Crucitti racconta che Obsydra e Pyrocladion, un tempo spesso in contrasto, stanno vivendo un periodo di buoni rapporti.","Il Crucitti attribuisce questo riavvicinamento alla crescente influenza del Culto del Fuoco, ma si tratta di una sua valutazione.","Al Varco della Scoria, gli avventurieri vedono un accolito del Culto e il motto «Il fuoco purifica. Il fuoco forgia». Non incontrano ostilità al loro ingresso in Obsydra."], questions:["Quale influenza esercita il Culto del Fuoco sulle due città-stato?","Il riavvicinamento fra Obsydra e Pyrocladion è davvero legato alla diffusione del culto?"], relations:["crucitti","brugheroccia","cato-mirel"]}
    ,{"slug":"spada-giuramento","name":"Spada lunga del Giuramento","type":"Arma magica · spada lunga","state":"Consegnata a Derrick","intro":"Antica spada lunga dalla lama annerita e fredda al tatto, con simboli quasi cancellati sull’elsa; dono del Vecchio Paladino Oscuro a Derrick Bombarrion.","facts":["Il Paladino Oscuro consegna l’arma a Derrick in punto di morte nella Cava di Obsydra.","Conferisce un bonus +1 ai tiri per colpire.","Giuramento Residuo (1/giorno): quando colpisce una creatura, chi la impugna può infliggere +1d6 danni necrotici, più ulteriori +1d6 se il bersaglio è già sotto la metà dei propri punti ferita."],"questions":["A quale giuramento era legata la spada?","Che legame esiste tra il suo precedente possessore e Derrick?"],"relations":["paladino-oscuro","cava-obsydra"]}
    ,{"slug":"anello-saltare","name":"Anello del Saltare","type":"Oggetto magico","state":"Recuperato dopo lo scontro con i grung","intro":"Un anello magico recuperato dal bottino di don Batraci e dei suoi seguaci nelle paludi di Nemorae.","facts":["La compagnia lo recupera dopo aver sconfitto la banda di grung guidata da don Batraci.","Viene trovato insieme a monete, oggetti di valore e ad alcune fiale di veleno.","È uno dei pochi bottini rilevanti ottenuti dallo scontro al ponticello."],"questions":["Da chi era stato sottratto prima di finire nelle mani della banda?"],"relations":["don-batraci","ponticello-grung","paludi-settentrionali"]},
    {"slug": "grandi-fauci", "name": "Le Grandi Fauci", "type": "Predatore delle paludi · coccodrillo gigante", "state": "Abbattuto dagli avventurieri", "intro": "Enorme coccodrillo che viveva nelle Acque Profonde e che, secondo gli abitanti di Roncenoir, era diventato una minaccia all’equilibrio della zona.", "facts": ["Lethraën riferisce che la creatura attacca animali e abitanti e ritiene doloroso ma necessario abbatterla.", "La compagnia la attira con una capra viva utilizzata come esca sulle rive delle Acque Profonde.", "Insieme al coccodrillo gigante arrivano altri due coccodrilli; gli avventurieri abbattono tutti e tre i predatori.", "La sconfitta del mostro è ricompensata da Lethraën con la Caraffa dell’Acqua Eterna."], "relations": ["acque-profonde", "roncenoir", "lethraen", "caraffa-acqua-eterna"]},
    {"slug": "caraffa-acqua-eterna", "name": "Caraffa dell’Acqua Eterna", "type": "Oggetto magico", "state": "In possesso della compagnia", "intro": "Una caraffa magica capace di produrre acqua, donata da Lethraën dopo la caccia alle Grandi Fauci.", "facts": ["Lethraën la consegna come ricompensa per aver eliminato il predatore che minacciava l’equilibrio naturale attorno a Roncenoir.", "Si tratta di un oggetto magico capace di produrre acqua."], "relations": ["lethraen", "roncenoir", "grandi-fauci"]},
    {"slug": "grande-piaga", "name": "La Grande Piaga", "type": "Calamità antica · testimonianza", "state": "Narrata da Lethraën", "intro": "Terribile calamità ricordata da Lethraën come parte della catastrofe avvenuta circa ottocento anni prima, quando l’Abisso si riversò sul Surturheim.", "facts": ["Secondo il racconto di Lethraën, l’evento fu accompagnato dall’apparizione di demoni nel Surturheim.", "L’anziano sostiene che la Piaga corrompesse ciò che toccava e indica il proprio braccio pietrificato come una conseguenza.", "Durante quei disastri, comunità di kenku abbandonarono il Surturheim e cercarono rifugio in Nemorae.", "Lethraën racconta che la disperata ricerca di risorse degli esuli suscitò una risposta brutale da parte degli elfi e delle creature della foresta, culminata in un genocidio di cui porta ancora il rimorso."], "questions": ["Quale fu l’origine della catastrofe?", "Qual era la natura della Piaga e quanto si diffuse?", "Quanto della tragedia degli esuli kenku è ancora conosciuto?"], "relations": ["lethraen", "roncenoir"]}
  ]
};
