/* CRONACHE DI THESPIRA — CONTENUTI PUBBLICI
 * SOLO informazioni che la compagnia conosce. Mai inserire materiale del DM.
 * Per aggiungere un capitolo, pubblicarlo qui e aggiornare published: true.
 */
const CHRONICLES = {
  updated: "08 ottobre 2026 · ritratti di Selese e Cato",
  current: {
    place: "Ebavurage · Le Due Lanterne",
    subtitle: "A metà giornata, la compagnia esamina l'equipaggiamento della bottega. Nessun acquisto è ancora stato effettuato.",
    next: "Alina ha chiesto agli avventurieri di raggiungere la vecchia fattoria Bellier la notte seguente."
  },
  chapters: [
    {number:"I", slug:"manna", title:"Manna e Lilith-Zetto", region:"Nemorae", published:true, description:"La nascita della compagnia, i rapimenti nelle foreste e una pagina indecifrabile."},
    {number:"II", slug:"reietti", title:"L’ordine di Selese Arco", region:"Nemorae", published:true, description:"L’ordine del Settenario Aureo, l’incontro con Nero e la scelta di difendere i reietti."},
    {number:"III", slug:"lantrelle", title:"Il rapporto di Lantrelle", region:"Nemorae", published:true, description:"La menzogna di Tomato, l'armatura di Derrick, l'intervento di Cato Mirel e la nuova missione."},
    {number:"IV", slug:"brugheroccia", title:"Il Babau di Brugheroccia", region:"Surturheim", published:true, description:"Una richiesta d’aiuto lungo il Lirion, un demone nelle miniere e l’ospitalità del Crucitti."},
    {number:"V", slug:"obsydra", title:"Obsydra e la Cava", region:"Surturheim", published:false, description:"La ricerca della pagina e il Vecchio Paladino Oscuro."},
    {number:"VI", slug:"paludi", title:"Le paludi di Nemorae", region:"Nemorae", published:false, description:"La via per Roncenoir e la gang di don Batraci."},
    {number:"VII", slug:"roncenoir", title:"Roncenoir", region:"Nemorae", published:false, description:"Giotis Pana, Lethraën e le Grandi Fauci."},
    {number:"VIII", slug:"gola", title:"La strada per Heliara", region:"Nemorae", published:false, description:"Il viaggio e l'incontro con Mercer Berus."},
    {number:"IX", slug:"ebavurage", title:"Ebavurage", region:"Nemorae", published:false, description:"Il borgo, il bestiame massacrato e i sospetti dei suoi abitanti."}
  ],
  people: [
    {slug:"wilhelm-codroipo", name:"Wilhelm Codroipo", role:"Locandiere", where:"Manna", intro:"Gestisce il Cervo Sonnacchioso, la locanda in cui cinque futuri compagni hanno incrociato le proprie strade.", facts:["Durante una serata al Cervo Sonnacchioso, un gruppo di avventori rivolge offese transfobiche a Wilhelm.","Akros, Baldur, Derrick, Orgen e Tomato intervengono nella rissa e allontanano gli aggressori.","Wilhelm ringrazia i cinque offrendo vitto e alloggio."], relations:["manna","cervo-sonnacchioso"]},
    {slug:"margravio", name:"Il Margravio di Manna", role:"Amministratore del villaggio", where:"Manna", intro:"Un ometto pomposo che si presenta come Margravio e si occupa dell'amministrazione di Manna.", facts:["Affida ai sei avventurieri il compito di fermare Lilith-Zetto.","Riferisce che una bambina è stata rapita e che altri bambini scomparsi non sono mai tornati."], relations:["manna"]},
    {slug:"vecchio", name:"Il vecchio della foresta", role:"Identità sconosciuta", where:"Foreste di Nemorae", intro:"Uno sconosciuto dall'aspetto stanco, incontrato durante la ricerca di Lilith-Zetto.", facts:["Dissolve due spaventapasseri animati semplicemente posando loro una mano sulla schiena.","Ospita la compagnia nella propria baracca e fornisce indicazioni per raggiungere la megera.","Dopo la scomparsa lascia a Brann un messaggio: sa del furto della pagina, ma vuole che il kenku la conservi."], relations:["baracca","prima-pagina"]},
    {slug:"lilith-zetto", name:"Lilith-Zetto", role:"Megera Verde · sconfitta", where:"Foreste di Nemorae", intro:"Una Megera Verde responsabile di ripetuti rapimenti di bambini nelle vicinanze di Manna.", facts:["Gli avventurieri la raggiungono nel suo antro dopo aver combattuto alcuni spaventapasseri animati.","La compagnia riesce a sconfiggerla.","La bambina rapita più di recente non può essere salvata."], relations:["antro-megera","manna"]},
    {slug:"selese-arco", name:"Magistra Selese Arco", image:"assets/selese-arco-portrait.png", role:"Magistra · Settenario Aureo", where:"Manna · Cervo Sonnacchioso", intro:"Esponente del Settenario Aureo, il gruppo d’élite della Chiesa di Amaunator. La compagnia la incontra dopo essere tornata da Lilith-Zetto.", facts:["Raggiunge il Cervo Sonnacchioso accompagnata da quattro guardie, indossando abiti bianchi, oro e blu.","Accusa il gruppo di avere intralciato un’indagine della Chiesa nelle Foreste di Nemorae, che comprendeva anche le attività di Lilith-Zetto.","Ordina agli avventurieri di rintracciare e sterminare un gruppo di nomadi provenienti da Heliara, che presenta come traditori della Chiesa.","Chiede loro di fare rapporto a Lantrelle. La compagnia finirà per schierarsi dalla parte dei perseguitati.","A Lantrelle riconosce l'armatura di un ufficiale della Chiesa indossata da Derrick, compromettendo il falso rapporto di Tomato.","Cato Mirel ipotizza davanti a lei un secondo scopo nell'invio di due ufficiali considerati ‘impuri’ per una presunta relazione omosessuale; Selese si irrigidisce ma non insiste."], relations:["cervo-sonnacchioso","manna","accampamento-reietti","lantrelle","cato-mirel"]},
    {slug:"nero", name:"Nero", role:"Viaggiatore misterioso", where:"A nord di Manna", intro:"Uno sconosciuto vestito di nero e con un vistoso cilindro, incontrato lungo la ricerca dell’accampamento dei reietti.", facts:["La compagnia lo salva da un androsfinge.","Per ringraziare gli avventurieri dona loro quattro Anelli del Camminare sull’Acqua."], relations:["anelli-acqua","foreste-nemorae"]},
    {slug:"arel", name:"Arel", role:"Bambino dell’accampamento", where:"Accampamento dei reietti", intro:"Un bambino soccorso dagli avventurieri lungo il viaggio a nord di Manna.", facts:["Fa parte dell’accampamento cercato dalla compagnia e, senza comprenderne le intenzioni iniziali, ve la conduce.","Viene ucciso durante l’assalto di uomini con le insegne della Chiesa di Amaunator."], relations:["accampamento-reietti"]},
    {slug:"brannor", name:"Brannor", role:"Reietto · ex funzionario della Chiesa", where:"Accampamento dei reietti", intro:"Uno degli uomini dell’accampamento che offre agli avventurieri cena e ospitalità.", facts:["Accoglie la compagnia per la sera e la notte.","Il mattino dopo l’assalto riferisce che i reietti erano stati funzionari della Chiesa di Amaunator.","Secondo il suo racconto, il fratello è stato assassinato a Heliara dopo avergli confidato che la Chiesa cercava segretamente un antico diario.","Sostiene che Selese Arco sia stata inviata per eliminare eventuali testimoni di questa ricerca."], relations:["accampamento-reietti","antico-diario"]},
    {slug:"cato-mirel", name:"Magistro Cato Mirel", image:"assets/cato-mirel-portrait.png", role:"Magistro · Settenario Aureo", where:"Lantrelle", intro:"Un giovanissimo Magistro dai capelli biondi, allegro e apparentemente ingenuo; dietro i modi cordiali mostra un intuito particolarmente acuto.", facts:["La compagnia lo incontra mentre conversa con Selese Arco a Lantrelle.","Interviene quando Selese scopre la menzogna degli avventurieri, grazie anche all'armatura di un ufficiale della Chiesa indossata da Derrick.","Suggerisce che Selese avesse inviato all'accampamento due ufficiali considerati da lei ‘impuri’ perché accusati di avere una relazione omosessuale: nella lettura di Cato, qualsiasi esito dello scontro le sarebbe convenuto.","Selese si irrigidisce, ma lascia cadere il confronto.","Propone alla compagnia un nuovo test: recuperare per lui una pagina rinvenuta nelle miniere di Obsydra.","Consiglia di visitare l'Emporio del Brambilla."], relations:["lantrelle","selese-arco","pagina-obsydra","emporio-brambilla","culto-fuoco"]},
    {slug:"brambilla", name:"Il Brambilla", role:"Mercante", where:"Emporio del Brambilla", intro:"Un energico affarista brianzolo dall'accento milanese e dai modi decisi, incontrato dalla compagnia dopo il colloquio con Cato Mirel.", facts:["Gestisce l'Emporio del Brambilla, consigliato ai protagonisti da Cato.","I suoi modi sanguigni, spietatamente commerciali e caricaturali suscitano molte risate al tavolo.","La compagnia acquista alcuni generi vari, senza oggetti particolarmente rilevanti per la cronaca."], relations:["emporio-brambilla","cato-mirel"]}
    ,{slug:"crucitti", name:"Il Crucitti", role:"Sindaco · locandiere · imprenditore", where:"Brugheroccia", intro:"Il Crucitti, uomo sulla settantina, pelato e con un folto pizzetto, è sindaco di Brugheroccia, gestisce la locanda e dirige l’impresa di passamaneria locale.", facts:["Dai modi bruschi, energici e quasi aggressivi, è un uomo onesto e affidabile: quando dà ordini gli abitanti si affrettano a eseguirli.","Dopo la sconfitta del Babau, consegna alla compagnia una ricompensa in oro e le offre vitto e alloggio, che gli avventurieri accettano.","Racconta che Obsydra e Pyrocladion, dopo molti contrasti, sono oggi in buoni rapporti.","Attribuisce personalmente il riavvicinamento alla crescente influenza del Culto del Fuoco in entrambe le città: è una sua opinione, non un fatto confermato."], relations:["brugheroccia","miniera-brugheroccia","culto-fuoco"]}
  ],
  places: [
    {slug:"manna", name:"Manna", type:"Villaggio", region:"Nemorae", intro:"Insediamento nelle Foreste di Nemorae, dove si sono incontrati i sei membri della compagnia.", facts:["Ospita la locanda del Cervo Sonnacchioso.","È amministrata da un individuo che si presenta come Margravio di Manna.","I suoi abitanti hanno sofferto per i rapimenti compiuti da Lilith-Zetto."], relations:["cervo-sonnacchioso","foreste-nemorae"]},
    {slug:"cervo-sonnacchioso", name:"Il Cervo Sonnacchioso", type:"Locanda", region:"Manna", intro:"Locanda di Wilhelm Codroipo, teatro della rissa che ha riunito i primi cinque avventurieri.", facts:["Tomato vi suona la baggopipa per guadagnarsi vitto e alloggio.","Gli avventori che insultano Wilhelm e Tomato vengono messi alla porta.","Wilhelm offre vitto e alloggio ai cinque che sono intervenuti."], relations:["manna"]},
    {slug:"foreste-nemorae", name:"Foreste di Nemorae", type:"Regione boschiva", region:"Nemorae", intro:"Le vaste foreste attraversate dalla compagnia durante le prime avventure.", facts:["Brann incontra un branco di lupi dopo aver rubato la baggopipa di Tomato.","Gli avventurieri combattono gli spaventapasseri animati durante la ricerca di Lilith-Zetto.","La baracca di un vecchio misterioso e l'antro della megera si trovano al loro interno."], relations:["baracca","antro-megera"]},
    {slug:"baracca", name:"La baracca del vecchio", type:"Abitazione isolata", region:"Foreste di Nemorae", intro:"Rifugio dello sconosciuto che aiuta la compagnia contro gli spaventapasseri.", facts:["La compagnia vi trascorre una notte.","Brann vi trova e sottrae una pagina coperta di simboli incomprensibili.","Al ritorno, il vecchio non c'è più; rimane un messaggio destinato a Brann."], relations:["foreste-nemorae","prima-pagina"]},
    {slug:"antro-megera", name:"L'antro di Lilith-Zetto", type:"Nascondiglio", region:"Foreste di Nemorae", intro:"Il rifugio della Megera Verde, raggiunto dalla compagnia seguendo le indicazioni del vecchio.", facts:["Qui la compagnia affronta e sconfigge Lilith-Zetto.","La bambina rapita non può essere salvata."], relations:["foreste-nemorae"]},
    {slug:"accampamento-reietti", name:"L’accampamento dei reietti", type:"Accampamento itinerante", region:"A nord di Manna · Nemorae", intro:"Accampamento mobile di un gruppo di persone originarie di Heliara, descritte da Selese Arco come pericolosi traditori della Chiesa.", facts:["Arel, un bambino salvato dagli avventurieri, conduce il gruppo all’accampamento.","Brannor offre agli avventurieri cena e ospitalità.","Durante la cena uomini con le insegne della Chiesa attaccano il campo e uccidono Arel.","La compagnia si schiera con gli abitanti dell’accampamento e sconfigge gli assalitori."], relations:["arel","brannor","selese-arco"]},
    {slug:"lantrelle", name:"Lantrelle", type:"Avamposto commerciale", region:"Nemorae", intro:"Avamposto commerciale a nord-est di Manna, al riparo dall'influenza diretta della Chiesa grazie alla protezione della Regina Veyra.", facts:["Selese Arco vi attende il rapporto sulla missione contro i reietti.","La compagnia incontra qui Magistro Cato Mirel.","Il falso rapporto di Tomato viene compromesso dall'armatura di un ufficiale della Chiesa indossata da Derrick.","Cato interrompe l'inasprimento del confronto e propone una missione a Obsydra."], relations:["selese-arco","cato-mirel","pagina-obsydra"]},
    {slug:"emporio-brambilla", name:"Emporio del Brambilla", type:"Emporio per avventurieri", region:"Tappa successiva a Lantrelle", intro:"Bottega raccomandata da Cato Mirel per gli approvvigionamenti degli avventurieri. La posizione precisa non è ancora documentata nella cronaca.", facts:["Il mercante Brambilla si distingue per l'accento milanese, l'energia e la durezza nelle trattative.","La compagnia acquista generi vari, senza acquisti determinanti per l'avventura."], relations:["brambilla","cato-mirel"]}
    ,{slug:"brugheroccia", name:"Brugheroccia", type:"Borgo montano", region:"Surturheim", intro:"Piccolo e dignitoso borgo montano, isolato fra pendii spogli e scoscesi, con il grande fiume Lirion visibile nella valle sottostante.", facts:["Una miniera del luogo è teatro di fenomeni inquietanti: rumori, gelo persistente e un'oscurità anomala.","Gli avventurieri vengono fermati lungo la strada da minatori preoccupati per un compagno rimasto sottoterra.","Dopo la sconfitta del Babau, gli abitanti mostrano una riconoscenza sincera, senza organizzare festeggiamenti.","Il Crucitti, sindaco e locandiere, ricompensa la compagnia con oro, vitto e alloggio; gli avventurieri pernottano nel borgo."], relations:["crucitti","miniera-brugheroccia","lirion","babau-brugheroccia"]},
    {slug:"miniera-brugheroccia", name:"La miniera di Brugheroccia", type:"Miniera", region:"Brugheroccia · Surturheim", intro:"Complesso sotterraneo con alcune diramazioni, nel quale un minatore è rimasto mentre si manifestavano fenomeni inspiegabili.", facts:["I lavoratori riferiscono rumori, gelo persistente e un buio eccezionalmente fitto.","Un crollo impone una breve deviazione e la compagnia affronta alcuni Mephit di terra.","In una camera sotterranea il gruppo scopre il corpo smembrato del minatore disperso.","Dall'oscurità emerge un Babau che sorprende Baldur; la compagnia affronta e sconfigge il demone."], relations:["brugheroccia","babau-brugheroccia"]},
    {slug:"lirion", name:"Fiume Lirion", type:"Fiume", region:"Nemorae · Surturheim", intro:"Grande corso d'acqua costeggiato dalla strada che conduce la compagnia fuori dalle Foreste di Nemorae e verso il Surturheim.", facts:["Il viaggio per Obsydra segue per un tratto il corso del fiume.","Il Lirion è visibile dalla valle sottostante Brugheroccia."], relations:["brugheroccia","foreste-nemorae"]}
  ],
  discoveries: [
    {slug:"prima-pagina", name:"La prima pagina", type:"Oggetto misterioso", state:"Origine sconosciuta", intro:"Una pagina ricoperta di segni incomprensibili, trovata da Brann nella baracca del vecchio.", facts:["Brann se ne impossessa durante la notte trascorsa nella baracca.","Il vecchio sa del furto e, nel messaggio lasciato prima di scomparire, chiede che sia Brann a conservarla.","Al termine della prima avventura nessuno della compagnia è in grado di interpretarne i simboli."], questions:["Chi ha scritto la pagina?","Che cosa significano i simboli?","Perché il vecchio ha deciso di lasciarla a Brann?"], relations:["baracca","vecchio"]},
    {slug:"anelli-acqua", name:"Anelli del Camminare sull’Acqua", type:"Oggetti magici", state:"Quattro anelli ricevuti", intro:"Quattro anelli consegnati da Nero agli avventurieri come ringraziamento per averlo salvato da un androsfinge.", facts:["Nero dona alla compagnia quattro Anelli del Camminare sull’Acqua.","L’incontro avviene durante il viaggio alla ricerca dei reietti a nord di Manna."], relations:["nero"]},
    {slug:"antico-diario", name:"Il diario ricercato dalla Chiesa", type:"Testimonianza e mistero", state:"Notizia riferita da Brannor", intro:"Secondo Brannor, la Chiesa di Amaunator cerca un antico diario nel massimo segreto.", facts:["Brannor sostiene che suo fratello gli abbia parlato dell’operazione a Heliara.","Riferisce che il fratello è stato ucciso poco dopo quella confidenza.","Brannor collega a questa scoperta la persecuzione degli ex funzionari della Chiesa fuggiti dall’accampamento."], questions:["Di quale diario si tratta?","Perché la Chiesa lo cerca?","Esiste un legame con la pagina trovata da Brann?"], relations:["brannor","prima-pagina"]},
    {slug:"pagina-obsydra", name:"La pagina segnalata a Obsydra", type:"Reliquia da recuperare", state:"Segnalata da Cato Mirel", intro:"Una pagina emersa dalle miniere di Obsydra, che Cato Mirel sostiene appartenga di diritto alla Chiesa di Amaunator.", facts:["Cato riferisce di aver tentato senza successo di recuperarla a Obsydra.","Gli abitanti del Surturheim, perlopiù fedeli al Culto del Fuoco, sono diffidenti verso le insegne della Chiesa.","Il Magistro affida il recupero alla compagnia, ritenendo che avventurieri non conosciuti sul posto possano avere maggior fortuna."], questions:["Che cosa contiene la pagina?","Ha qualche rapporto con quella trovata da Brann?","Perché la Chiesa desidera recuperarla?"], relations:["cato-mirel","prima-pagina","lantrelle"]},
    {slug:"armatura-ufficiale", name:"L'armatura dell'ufficiale", type:"Equipaggiamento recuperato", state:"Indossata da Derrick a Lantrelle", intro:"Armatura appartenuta a un ufficiale della Chiesa caduto nello scontro all'accampamento dei reietti.", facts:["Derrick recupera e indossa l'armatura dopo lo scontro.","A Lantrelle Selese la riconosce mentre Tomato tenta di sostenere un falso rapporto.","La scoperta fa precipitare il confronto con la Magistra."], relations:["selese-arco","lantrelle","accampamento-reietti"]}
    ,{slug:"babau-brugheroccia", name:"Il Babau di Brugheroccia", type:"Creatura abissale", state:"Sconfitto nella miniera", intro:"Demone abissale riconosciuto dalla compagnia nelle profondità della miniera di Brugheroccia. Creature simili sono solitamente legate alle leggende di Thespira.", facts:["La sua presenza è accompagnata da un'oscurità anomala e da una sensazione di gelo persistente.","Nella camera in cui si nasconde si trova il corpo smembrato di un minatore.","Baldur è colpito a sorpresa dopo essersi avvicinato al corpo; il combattimento è impegnativo, ma la compagnia uccide il demone.","L'incontro richiama gli ammonimenti del misterioso vecchio della foresta, senza stabilire che i due episodi siano collegati."], questions:["Come è arrivato un demone abissale nella miniera?","La sua presenza è un caso isolato?"], relations:["miniera-brugheroccia","vecchio","brugheroccia"]},
    {slug:"culto-fuoco", name:"Il Culto del Fuoco nel Surturheim", type:"Culto religioso · notizie raccolte", state:"Informazioni riferite da Cato Mirel e dal Crucitti", intro:"Culto radicato nel Surturheim, al quale secondo quanto riferito alla compagnia sono particolarmente legate Obsydra e Pyrocladion.", facts:["Cato Mirel afferma che la devozione locale al Culto del Fuoco contribuisce alla diffidenza verso la Chiesa di Amaunator.","Il Crucitti racconta che Obsydra e Pyrocladion, un tempo spesso in contrasto, stanno vivendo un periodo di buoni rapporti.","Il Crucitti attribuisce questo riavvicinamento alla crescente influenza del Culto del Fuoco, ma si tratta di una sua valutazione."], questions:["Quale influenza esercita il Culto del Fuoco sulle due città-stato?","Il riavvicinamento fra Obsydra e Pyrocladion è davvero legato alla diffusione del culto?"], relations:["crucitti","brugheroccia","cato-mirel"]}
  ]
};
